### ISSUE TITLE
Remove all conditional parts around macro _WITH_REFRACT_

### ISSUE THREAD

**Issue by klokane** [apiaryio/drafter#103]
Refract is used in both types of AST (refract/ast) we should remove all around this define

**Comment by pksunkara** [comment]
This is not going to be done anytime soon since we decided that we still want the old MSON to exist in the code for some time.

**Comment by klokane** [comment]
We can do it without removing old code.
Respective there is too many places depended on given macro, and switch between old/new MSON style is in just one place. All other macro related part can be removed
