### ISSUE TITLE
Add nullable type attribute

### ISSUE THREAD

**Issue by obihann** [apiaryio/drafter#106]
Based on apiaryio/mson#38 the nullable type attribute should be added. Examples of used and rendering can be found in the pull request.

If I understand this project correctly *drafter* is essentially a wrapper for *[apiaryio/snowcrash](https://github.com/apiaryio/snowcrash)*, which means this addition will not actually be part of drafter but *apiaryio/snowcrash* itself. Once the change is made in *[apiaryio/snowcrash](https://github.com/apiaryio/snowcrash)* then *drafter* will simply be updated to include the latest version of *[apiaryio/snowcrash](https://github.com/apiaryio/snowcrash)*... Am I close here?

if so then apiary/snowcrash#347 will be related to this as that issue is for the implementation of `nullable` in *[apiaryio/snowcrash](https://github.com/apiaryio/snowcrash)*.

**Comment by pksunkara** [comment]
The parsing should be added to apiaryio/snowcrash, but the rendering support should be added apiaryio/drafter

**Comment by obihann** [comment]
Thanks. I will start with apiaryio/snowcrash and when that is merged, carry on to this.
