### ISSUE TITLE
Unable to render when named types are nested in array

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#117]
Given the below blueprint, 

```apib
# GET /
+ Response 200 (application/json)
    + Attributes (array[User])
​
# Data Structures
## User
+ username: pksunkara
```

The `payload.body` is not getting rendering because there is a problem with expanding MSON.

**Comment by obihann** [comment]
@pksunkara I'll start looking into this now.

**Comment by obihann** [comment]
@pksunkara do you have a sample JSON output of what this should look like? I have a rough idea but I want to be sure I'm on the right track.

**Comment by kylef** [comment]
I'd expect it would be rendered as:

```json
{
  "username": "pksunkara"
}
```

**Comment by obihann** [comment]
@kylef so from what I see the overall structure is fine, however their is no JSON body, and you provided what that should look like. I'll get started on this now.

**Comment by obihann** [comment]
@pksunkara @kylef I'm still looking into this however I'm not making much progress. I'm feeling that this is related to the serialization of the MSON however wouldn't most of that be handled within snowcrash itself?

**Comment by obihann** [comment]
I'm going to step aside from this for a little while incase somebody else wants to take a stab at it.

**Comment by pksunkara** [comment]
When the above blueprint is parsed using the master branch, this is the output.

```json
{
  "element": "category",
  "meta": {
    "classes": [
      "api"
    ],
    "title": ""
  },
  "content": [
    {
      "element": "category",
      "meta": {
        "classes": [
          "resourceGroup"
        ],
        "title": ""
      },
      "content": [
        {
          "element": "resource",
          "meta": {
            "title": ""
          },
          "attributes": {
            "href": "/"
          },
          "content": [
            {
              "element": "transition",
              "meta": {
                "title": ""
              },
              "content": [
                {
                  "element": "httpTransaction",
                  "content": [
                    {
                      "element": "httpRequest",
                      "attributes": {
                        "method": "GET"
                      },
                      "content": []
                    },
                    {
                      "element": "httpResponse",
                      "attributes": {
                        "statusCode": "200",
                        "headers": {
                          "element": "httpHeaders",
                          "content": [
                            {
                              "element": "member",
                              "content": {
                                "key": {
                                  "element": "string",
                                  "content": "Content-Type"
                                },
                                "value": {
                                  "element": "string",
                                  "content": "application/json"
                                }
                              }
                            }
                          ]
                        }
                      },
                      "content": [
                        {
                          "element": "dataStructure",
                          "content": [
                            {
                              "element": "array"
                            }
                          ]
                        },
                        {
                          "element": "asset",
                          "meta": {
                            "classes": "messageBody"
                          },
                          "attributes": {
                            "contentType": "application/json"
                          },
                          "content": "[]"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "element": "category",
      "meta": {
        "classes": [
          "dataStructures"
        ]
      },
      "content": [
        {
          "element": "dataStructure",
          "content": [
            {
              "element": "object",
              "meta": {
                "id": "User"
              },
              "content": [
                {
                  "element": "member",
                  "content": {
                    "key": {
                      "element": "string",
                      "content": "username"
                    },
                    "value": {
                      "element": "string",
                      "content": "pksunkara"
                    }
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
```

As you can see, the `dataStructure` element inside the `httpResponse` is not correctly expanded which effects the serialising and rendering.

**Comment by obihann** [comment]
@pksunkara Thanks for this. So do you think exists in `refract/RenderJSONVisitor.cc` when it is stepping through the elements or prior to that when the elements are serialized?

**Comment by pksunkara** [comment]
Prior to that. I have even said that the issue is when converting the data structures to refract which happens in `MSONToRefract`

**Comment by obihann** [comment]
@pksunkara thanks, I'll dive into that and see if I can come up with something.

**Comment by kylef** [comment]
I've had a look into this one. From what I understand is the issue is from converting the MSON data structure to a refract element (from within `MSONToRefract`). Inside `RefractElementFromMSON` it seems if there are no sections, no information will make it into the `ElementData` and subsequently the element.

```cpp
ElementData<T> data;
std::for_each(ds.sections.begin(), ds.sections.end(), ExtractTypeSection<T>(data, ds));
TransformElementData<T>(element, data);
```

Perhaps the issue is in snowcrash and the section shouldn't be empty, but I don't know much about these details and if that's correct.

You can see the MSON attribute structure as follows:

![screen shot 2015-10-15 at 21 30 54](https://cloud.githubusercontent.com/assets/44164/10533867/17492bcc-7384-11e5-8dba-c9e6987794b1.png)

Where you can see that the nested type for `User` exists but the sections is empty.

This results in an element as which doesn't have any information about the `User` type:

![screen shot 2015-10-15 at 21 30 12](https://cloud.githubusercontent.com/assets/44164/10533868/182e61ce-7384-11e5-9d5f-c6a50f4e8b6d.png)

**Comment by pksunkara** [comment]
> Perhaps the issue is in snowcrash and the section shouldn't be empty, but I don't know much about these details and if that's correct.

That is incorrect. Sections should be empty in this case. It's just when we are doing `MSONToRefract`, we need to make sure that `nestedTypes` are also taken into consideration.

**Comment by obihann** [comment]
@pksunkara It seems that when in `MSONToRefract` arrays of a nested type are being handled through this block:

```c++
            case mson::ObjectTypeName:
            case mson::UndefinedTypeName:
                element = RefractElementFromMSON<refract::ObjectElement>(dataStructure);
                break;
```
Should then not actually be handled though this one?
```c++
            case mson::EnumTypeName:
            case mson::ArrayTypeName:
                element = RefractElementFromMSON<refract::ArrayElement>(dataStructure);
                break;
```

**Comment by obihann** [comment]
@pksunkara I commented earlier today with a false assumption that we never hitting `case mson::ArrayTypeName:` (line 813) of `MSONToRefract` (line 789) in `RefractDataStructure.cc` however I since realized we do hit that. I believe now that the issue is *prior* to this function though, and the reason is that when we loop through the data structures not only does the specific element have no value, it's base name is `UndefinedTypeName`. Below are some screenshots to hopefully help. I'm going to look into some of the code prior to this and not 100% rule out snowcrash.

![screen shot 2015-10-19 at 10 13 48 am](https://cloud.githubusercontent.com/assets/1507841/10578910/83a8e6b2-764b-11e5-8216-4139df4c9c13.png)
<img width="453" alt="screen shot 2015-10-19 at 10 19 24 am" src="https://cloud.githubusercontent.com/assets/1507841/10578909/83a88f6e-764b-11e5-93dc-4d24599e2142.png">

**Comment by obihann** [comment]
After spending a lot of time today walking through the debugger I'm starting to see now the issue is not with snowcrash, and it is in drafter as @pksunkara originally stated. Ignore my previous comments.

**Comment by obihann** [comment]
It seems that in `RegisterNamedTypes` (line 87) of `RefractAPI.cc` it is properly adding the type (in this case User), so it is later on that the bug exists. I'll keep debugging and post my notes as I go, I think I'm on to something though.

**Comment by obihann** [comment]
One thing I'm seeing, and this could be a misunderstanding on my part, is in the snowcrash element, their are two content elements, one for the request and another for the data structures. The data structures looks fine however the request itself though it shows an element that should be the array of users, is empty. Their seems to be no connection at all between the request and the data structure. Perhaps that is the issue, and if so I'm not sure where to look next.

**Comment by obihann** [comment]
@pksunkara is it correct to say that in `RefractAPI.cc` line 446 `BlueprintToRefract` is where the array elements are created and this is likely where we need to be checking against named types?
