### ISSUE TITLE
empty and optional elements appear in json body

### ISSUE THREAD

**Issue by obihann** [apiaryio/drafter#121]
The following blueprint:

```md
# GET /
+ Response 200 (application/json)
    + Attributes
        + s1 (optional)
```
Renders the following JSON example

```json
"content": "{\n  \"s1\": \"\"\n}"
```

`s1` should not be part of the body, because it is both empty and optional.

**Comment by obihann** [comment]
This was discovered in https://github.com/apiaryio/drafter/pull/116#discussion_r40329540

**Comment by zdne** [comment]
:+1: good catch!

**Comment by obihann** [comment]
Thanks, I'm going to try and get you a PR for this over the weekend.

**Comment by obihann** [comment]
@zdne when a field is both optional and nullable, and without a value, should we a) not show it or b) list it as null?

### example:

```mson
+ s1 (optional, nullable)
```

### solution a:

```json
{}
```

### solution b:

```json
{
   "s1": null
}
```

I am leaning towards option a unless they define a value (which of course can be `null`), but I could be persuaded either way :+1:

**Comment by obihann** [comment]
#130 implements solution a.

**Comment by pksunkara** [comment]
If you remember, we had decided on giving preference to `nullable` in https://github.com/apiaryio/mson/pull/38/files#diff-b445aff023fbb884a212dd2b74cec7a3R55. Please do that instead of changing it.

**Comment by pksunkara** [comment]
Looks like #130 actually implemented solution b which is the correct solution.

**Comment by obihann** [comment]
Sorry about the mistakes, I probably should have gone to sleep then coded this in the morning. I'll tidy it up now.

**Comment by obihann** [comment]
#132 replaced #130 because I made a horrible rebase. This has now been merged into master and can be resolved.
