### ISSUE TITLE
Make fails with error: MarkdownNode.h: No such file or directory

### ISSUE THREAD

**Issue by cdanger** [apiaryio/drafter#128]
Hello, 
when running 'make' I get the fatal error : MarkdownNode.h: No such file or directory. 
For info, I am running this on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-65-generic x86_64).
Below is the full output. 

$ make drafter
make -C ./build V=1 drafter
make[1]: Entering directory `/home/cda/GIT-REPOS/drafter/build'
  g++ '-DBUILDING_SNOWCRASH=1' -I../ext/snowcrash/ext/markdown-parser/src -I../ext/snowcrash/ext/markdown-parser/ext/sundown/src -I../ext/sos/src -I../ext/snowcrash/src  -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -m64  -MMD -MF out/Release/.deps/out/Release/obj.target/libdrafter/src/drafter.o.d.raw  -c -o out/Release/obj.target/libdrafter/src/drafter.o ../src/drafter.cc
In file included from ../ext/snowcrash/src/BlueprintSourcemap.h:12:0,
                 from ../ext/snowcrash/src/snowcrash.h:12,
                 from ../src/drafter.h:12,
                 from ../src/drafter.cc:9:
../ext/snowcrash/src/Blueprint.h:16:26: fatal error: MarkdownNode.h: No such file or directory
 #include "MarkdownNode.h"
                          ^
compilation terminated.
make[1]: *** [out/Release/obj.target/libdrafter/src/drafter.o] Error 1
make[1]: Leaving directory `/home/cda/GIT-REPOS/drafter/build'
make: *** [drafter] Error 2

Any idea how I can fix this? 
Thanks for your help.

Regards,
Cyril

**Comment by pksunkara** [comment]
@cdanger Have you used `git submodule clone --recursive` to clone the drafter repo? It has a few submodules which you need init and update

**Comment by cdanger** [comment]
Yes, I did. I found out that the missing file(s) was caused by the “git clone” not being able to get the submodules with the URLs “git://….”, since my machine can reach Internet ONLY through a HTTP proxy. I had changed the URL in the git clone command to use “http://github.com/...” but not for the repo URLs of the submodules. So I used this trick from [1] to fix it:
$ git config --global url."https://".insteadOf git://

Works for me now ;)

Regards,
Cyril

[1] http://jgoodall.me/posts/2013/05/29/git-use-https/
