### ISSUE TITLE
Regression: Action Attributes not getting forwarded to Response

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#135]
#### Example

```apib
FORMAT: 1A

# Example

## GET /

+ Attributes
  + id: 123 (number)

+ Response 200 (application/json)
```

### Old behaviour

Response's body is

```json
{"id":123}
```

### New behaviour

Response's body is empty

### Expected

New behaviour is correct. From the [spec](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#action-attributes-description)

> If defined, all the Request sections of the respective Action section inherits these attributes unless specified otherwise.

So, the responses inside the action should not actually consider action attributes.

**Comment by pksunkara** [comment]
@zdne I think a few people are assuming that response attributes inherits from action attributes.

**Comment by zdne** [comment]
>  think a few people are assuming that response attributes inherits from action attributes.

@pksunkara do have any reference (eg. link to conversation). As you are stating the "new" (or better put "the fixed") behavior is the correct one – it it description of an action (input) attributes.

**Comment by pksunkara** [comment]
> do have any reference (eg. link to conversation)

I meant that statement because I did get a few regression diffs caused by this.

**Comment by zdne** [comment]
OK. Thanks for clarification. Closing.
