### ISSUE TITLE
Regression: Value for enum is not getting rendered

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#136]
# Example

```apib
FORMAT: 1A

# Example

# Data Structures
## A
+ a: TAC (B, required)

## B (enum)
- TAC

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

# Old behaviour

Response body is getting rendered as:

```json
{"a": "TAC"}
```

# New behaviour

```json
{"a": {}}
```

# Expected

Old behaviour is correct.

**Comment by klokane** [comment]
@pksunkara @zdne I've question, is prefered value `TAC` from `A` or `TAC` from `B` in this case?
It sounds weird, but I need to know from which source I should render value

**Comment by pksunkara** [comment]
It's from `A`. Because `B` might be something like this:

```apib
## B (enum)
- TAC
- CAT
```

**Comment by klokane** [comment]
@pksunkara sure, but `A` can be similar defined as  `+ a: TAC, CAT (B, required)`

**Comment by klokane** [comment]
/Ok lets assume this one definition
```## A
+ a: A,B (B, required)

## B (enum)
- C
- D
```

which one value to select?

**Comment by pksunkara** [comment]
Your example would  render `+ Attributes (A)` as `{ "a": "A,B" }`

**Comment by klokane** [comment]
`+ a: A,B (enum)` should be interreted as `[ `enum`, {}, {}, ["A", "B"] ]`
So i mean
```
## B (enum)
## A
+ a: A,B (B)
```
`A.a` should be interpreted in same way, because `B` is `enum`

**Comment by pksunkara** [comment]
@zdne We really **really** need your comment on this.

**Comment by zdne** [comment]
@pksunkara what is the question?

**Comment by klokane** [comment]
@zdne which value to pick for asset 
```
## A
+ a: A,B (B, required)

## B (enum)
- C
- D

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

**Comment by zdne** [comment]
@klokane for now the rule of the thumb should be:

1. value 
2. sample(s) (if value not present)
3. default (if value or sample(s) not present)

**Comment by zdne** [comment]
@klokane so question is what is the value of A

**Comment by zdne** [comment]
@klokane 

and I believe we have discussed the case 

```apib
- color: red, green (enum)
   - blue
   - cyan
```

**Comment by zdne** [comment]
obviously the one above does not make much sense. What does, however is:

```apib
- color: red
   - red
   - green
   - blue
```

And I believe from this is clear that red should get rendered.

**Comment by zdne** [comment]
The case 

```
- color: red, green (enum)
   - blue
   - cyan
```

Does not make much sense really, so I would just render `red` because it is the  first from `red`, `green` pair. Does this clarify?

**Comment by klokane** [comment]
There is no dispute :)
Question is is value "A, B", or "A" because 
`A, B` can be string but or array. Enum accept as value array.
I mean for `+ a: A,B (enum)` is it clear - value should be `A`
So i mean for definition  `+ a: A,B (B)` where `B` inherit from `enum` it should be same

**Comment by zdne** [comment]
it is odd that your value is same as the type name – is that intentional?

**Comment by klokane** [comment]
But @pksunkara means it should be `"A, B"` presented as `string` for same case

**Comment by klokane** [comment]
> it is odd that your value is same as the type name 

no, does not care names

**Comment by zdne** [comment]
Guys if instead of the `enum` would be an array, what would be the answer?

**Comment by klokane** [comment]
is this correct? 
https://github.com/apiaryio/drafter/issues/136#issuecomment-155906266

**Comment by zdne** [comment]
@klokane https://github.com/apiaryio/drafter/issues/136#issuecomment-156062140

**Comment by klokane** [comment]
For
`+ a: A,B (array)` is result `[ "array", {}, {}, ["A", "B"] ]`
so i mean same for enum should be
`+ a: A,B (enum)` is result `[ "enum", {}, {}, ["A", "B"] ]`

**Comment by zdne** [comment]
correct

**Comment by klokane** [comment]
for array we should pick value `[ "A", "B" ]`
For enum it should be "A"

**Comment by zdne** [comment]
correct

**Comment by klokane** [comment]
So same should be for inheritance

**Comment by zdne** [comment]
👍
