### ISSUE TITLE
Compilation fails on OS X 10.10, Xcode 7

### ISSUE THREAD

**Issue by tomekc** [apiaryio/drafter#154]
I am unable to install drafter, below is tail of log output

```
Last 15 lines from /Users/tomek/Library/Logs/Homebrew/drafter/02.make:
  ./gyp-mac-tool flock out/Release/linker.lock clang++ -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -Lout/Release  -o "out/Release/drafter" out/Release/obj.target/drafter/src/main.o out/Release/obj.target/drafter/src/config.o out/Release/obj.target/drafter/src/reporting.o out/Release/libdrafter.a out/Release/libsos.a out/Release/libsnowcrash.a out/Release/libmarkdownparser.a out/Release/libsundown.a
Undefined symbols for architecture x86_64:
  "__Unwind_Resume", referenced from:
      CreateSerializer(std::string const&) in main.o
      _main in main.o
      sos::SerializeJSON::string(std::string const&, std::ostream&) in main.o
      sos::SerializeYAML::string(std::string const&, std::ostream&) in main.o
      std::vector<snowcrash::SourceAnnotation, std::allocator<snowcrash::SourceAnnotation> >::~vector() in main.o
      sos::Base::~Base() in main.o
      std::auto_ptr<std::vector<sos::Base, std::allocator<sos::Base> > >::~auto_ptr() in main.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [out/Release/drafter] Error 1
make: *** [drafter] Error 2
```

Are there any known issues?

**Comment by kylef** [comment]
Hi @tomekc, there isn't any known issues.

Would you be able to confirm that you ran the following to attempt to install Drafter?

```shell
$ brew install --HEAD https://raw.github.com/apiaryio/drafter/master/tools/homebrew/drafter.rb
==> Summary
🍺  /usr/local/Cellar/drafter/HEAD: 4 files, 1.0M, built in 110 seconds
```

Would you be able to run `brew doctor` and see if it detects any system problems.

**Comment by tomekc** [comment]
I learned that "Undefined references to _Unwind_Resume are caused by compiling with a GCC with a different stack unwinding method from that used by the library you're trying to link with."

Does drafter have any binary dependencies? Maybe some library from brew which I have compiled with previous Xcode?

**Comment by obihann** [comment]
Joining in on this, I also cannot build master branch via Xcode running OSX 10.10.5 and Xcode 7.

**Comment by pksunkara** [comment]
> Does drafter have any binary dependencies? Maybe some library from brew which I have compiled with previous Xcode?

No, it does not.

@obihann It is not related to this issue at all if you look closely.

**Comment by klokane** [comment]
Hi guys, I tried gcc 4.6, 4.8, 5.2 and clang 3.6, 3.8 everyone build drafter.
with exception gcc 5.2 have some problems with test because of `Catch` library used in tests.

If I understand correctly, there is new version of Xcode? 
Can you please check if there are not some "residual objects" compiled with previous version of compiler?

**Comment by klokane** [comment]
I'm not able to check it on OS X, I'm on linux

**Comment by tomekc** [comment]
I'm pretty sure there is something wrong in my environment. Apple now dropped gcc in favor of clang:

```
$ clang++ -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

And most likely there are some residual objects, as the error suggests that I am linking with library compiled with different compiler. Hence my question about binary dependencies: any libraries linked with -l flag which may possibly laying around my system built with "wrong" compiler.

**Comment by klokane** [comment]
There are are no binary dependencies, all is build from scratch.
Can you, please, check it with clear clone and build from shell
```
% make distclean ; ./configure -i ;  make -j ; make test -j
```

**Comment by klokane** [comment]
@tomekc any news about issue?

**Comment by pksunkara** [comment]
@tomekc Do you have any update this?

**Comment by tomekc** [comment]
Sorry guys for silence, I was just to give up on this. I tried on other similar machines, and builds flawlessly.

However, what's interesting, manual clone and build worked

```
git clone --recursive git@github.com:apiaryio/drafter.git
cd drafter
make distclean
./configure -i
make -j
```

where building using brew formulae (as advised in README) still fails.

**Comment by kylef** [comment]
Sorry for delay in getting back to this one. I wonder if Homebrew's own caches could be the problem here. Perhaps it's cached some object files from previous compiler versions.

Usually the caches are stored in `/Library/Caches/Homebrew` so could you delete this directory and also run `brew cleanup` and see if it solves your problem.

```shell
$ rm -fr /Library/Caches/Homebrew
$ brew cleanup
```

**Comment by kylef** [comment]
I think what I've proposed should resolve your problem, if that isn't the case please feel free to re-open the issue.
