### ISSUE TITLE
Source maps should not be printed if no option is given

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#16]
@klokane This is priority. Please fix this first. And also add an integration test.

```
pksunkara@apicave [drafter] #180 «pksunkara/update» →  ./bin/drafter 
# My API

What's up
_version: "3.0"
metadata: []
name: "My API"
description: "What's up\n"
element: "category"
resourceGroups: []
content: []
metadata: []
name: []
description: []
resourceGroups: []
content: []

OK.
```

The output AST should only be this:

```
_version: "3.0"
metadata: []
name: "My API"
description: "What's up\n"
element: "category"
resourceGroups: []
content: []
```

**Comment by zdne** [comment]
@pksunkara can you please elaborate and put in words what is wrong and why is it this important?

**Comment by pksunkara** [comment]
When no source map option is given, only the AST should be printed to the output stream. Currently, the drafter is print both the AST and the empty sourcemap AST to the stream.

**Comment by zdne** [comment]
Oh that additional

```
name: []
description: []
resourceGroups: []
content: []
```

is from source map?

**Comment by pksunkara** [comment]
Yup.

**Comment by klokane** [comment]
https://github.com/apiaryio/drafter/pull/18
