### ISSUE TITLE
Problems for installation on Windows

### ISSUE THREAD

**Issue by mm-gmbd** [apiaryio/drafter#173]
Following the instructions for installation on Windows, and I can't seem to make it very far. 

At first, I was having some issues where, for some submodules, git would fail to connect to some of the git repos and fail out. However, that seems to be due to performing `clone --recursive` behind a proxy (so, not a drafter issue, more of a git issue). After switching to an open network and trying again, the connection to submodule repositories was resolved and it seemed that everything would work properly, but after making it much further I eventually ended up with

    Failed to recurse into submodule path `ext/snowcrash`.

Looking back through the installation log, it appears that there are a few failures, including:

    error: unable to create file projects/XCode/CatchSelfTest/CatchSelfTestSingle.xcodeproj/project.xcworkspace.xcshareddata/CatchSelfTestSingle.xccheckout (Filename too long)
    Unable to checkout 'd7e1790347...' in submodule path 'ext/showcrash/ext/markdown-parser/test/ext/Catch'
    ...
    Failed to recurse into submodule path `ext/snowcrash/ext/markdown-parser`
    ....

Noticing the **Filename too long** error, I moved everything to C:\apiaryio\drafter and the `git clone --recursive https://github.com/apiaryio/drafter.git` seemed to work fine (may want to make a note that directory structure/length is important in installation notes).

Okay, next issue. After, `cd drafter` and `vcbuild.bat` (from VS2012 x64 Cross Tools Command Prompt), I get the following message:

    creating config.gypi
    creating config.mk
    creating makefiles
    Warning: Missing input files:
    ./build\ext\snowcrash\..\..\..\ext\snowcrash\src\Version.h
    All OK.
    Project files generated.
    Build skipped. To build, this file needs to run from VS cmd prompt.

Indeed, the file `apiaryio/drafter/ext/snowcrash/src/Version.h` is non-existent (the closest "V"-file being `ValuesParser.h`). I'll re-run the `git clone` and pipe the output to a file to ensure that no errors occurred...

Until then, any ideas?

Thanks,
-Max

**Comment by pksunkara** [comment]
This issue will be fixed soon. Please check the PR above.

**Comment by pksunkara** [comment]
Thanks for the bug report :)
