### ISSUE TITLE
Should use messageBodySchema instead of messageSchema

### ISSUE THREAD

**Issue by smizell** [apiaryio/drafter#190]
In using Drafter.js, a parse result contained `messageSchema` instead of `messageBodySchema`. The API Description spec says it should be `messageBodySchema`. 

https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md#properties-2

**Comment by w-vi** [comment]
Cheers, it is addressed in https://github.com/apiaryio/drafter/pull/191 ... that should get merged soon™

**Comment by smizell** [comment]
@w-vi Hooray! So fast :)

**Comment by w-vi** [comment]
fixed in merged #191
