### ISSUE TITLE
Sample of nested array doesn't propagate correctly to JSON

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#206]
**UPDATE:** See https://github.com/apiaryio/drafter/issues/206#issuecomment-168734683 for details.

-----------------

### The problem

```
+ dimensions (array)
    + *20, 30, 40* (array[number], fixed)
```

appears in schema as following:

```
    "20, 30, 40": {
      "type": "array",
      "items": [
        {
          "type": "number"
        }
      ]
    }
  },
  "required": [
    "20, 30, 40"
  ]
```

### Expected behavior

My MSON markup tries to say, that:

- there is property called `dimensions`
- the property is of type `array`
- element of the array may be a sub-array of exactly three numbers, for example 20, 30, 40

<img width="270" alt="screen shot 2016-01-04 at 17 01 43" src="https://cloud.githubusercontent.com/assets/283441/12093726/e1d368ca-b304-11e5-9980-a09904c95971.png">

### How to reproduce

My sample blueprint:

```apib
FORMAT: 1A

# Building Supply Store API

## Brick Type [/bricks/{id}]

+ Parameters
  + id: XYZ42 - ID of a brick type.
+ Attributes
  + id
  + name (string)
  + colors: red, brown (array)
  + dimensions (array)
    + *20, 30, 40* (array[number], fixed)

### Get Particular Brick Type [GET]

Attributes defined in resource are referenced from payload.

+ Request (application/json)
+ Response 200 (application/json; charset=utf-8)
  + Attributes (Brick Type)
```

My Drafter command:

```shell
$ drafter -v
v2.1.1
$ drafter test.apib -f json
```

My result:

```json
...
                            {
                              "element": "asset",
                              "meta": {
                                "classes": [
                                  "messageBody"
                                ]
                              },
                              "attributes": {
                                "contentType": "application/json; charset=utf-8"
                              },
                              "content": "{\n  \"id\": \"\",\n  \"name\": \"\",\n  \"colors\": [\n    \"red\",\n    \"brown\"\n  ],\n  \"dimensions\": [],\n  \"20, 30, 40\": []\n}"
                            },
                            {
                              "element": "asset",
                              "meta": {
                                "classes": [
                                  "messageBodySchema"
                                ]
                              },
                              "attributes": {
                                "contentType": "application/json; charset=utf-8"
                              },
                              "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"id\": {\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"type\": \"string\"\n    },\n    \"colors\": {\n      \"type\": \"array\"\n    },\n    \"dimensions\": {},\n    \"20, 30, 40\": {\n      \"type\": \"array\",\n      \"items\": [\n        {\n          \"type\": \"number\"\n        }\n      ]\n    }\n  },\n  \"required\": [\n    \"20, 30, 40\"\n  ]\n}"
                            }
...
```

The result can be re-parsed as:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "colors": {
      "type": "array"
    },
    "dimensions": {},
    "20, 30, 40": {
      "type": "array",
      "items": [
        {
          "type": "number"
        }
      ]
    }
  },
  "required": [
    "20, 30, 40"
  ]
}
```

**Comment by w-vi** [comment]
If you indent the line ` + *20, 30, 40* (array[number], fixed)` by two more spaces it all of a sudden seems to work.

**Comment by kylef** [comment]
@honzajavorek I think the problem here is that all the list items are incorrectly indented by 2 spaces instead of 4 spaces in your example blueprint.

**Comment by honzajavorek** [comment]
@kylef Is that a feature? Does blueprint *require* me to write markdown lists with indentation of four?

-----------

If correctly indented as you two say, there's still a (different) bug, with sample value in JSON:

```
    + dimensions (array)
        + *20, 30, 40* (array[number], fixed)
```

<img width="702" alt="screen shot 2016-01-04 at 17 52 32" src="https://cloud.githubusercontent.com/assets/283441/12095106/e14bd8ee-b30c-11e5-9dec-3767c12b7c6e.png">

Following means a different thing (does not constraint the array to be exactly tuple of three), but works:

```
    + dimensions (array)
        + 20, 30, 40 (array[number])
```

**Comment by kylef** [comment]
@honzajavorek There isn't really a formal specification for markdown, but Gruber's "Syntax" documentation for Markdown (https://daringfireball.net/projects/markdown/syntax) says the following:

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab.

**Comment by honzajavorek** [comment]
Ah, I didn't know that. Thanks! Every day new skill.

**Comment by w-vi** [comment]
It actually is a bug in snowcrash see https://github.com/apiaryio/snowcrash/issues/286

**Comment by pksunkara** [comment]
I am closing this. Please refer to the above linked issue.
