### ISSUE TITLE
Remove head-only requirement from homebrew package

### ISSUE THREAD

**Issue by benjaminjackson** [apiaryio/drafter#214]
I've already been bitten by this once when the library was updated to 1.0; my scripts were built against 0.x library and it took forever to figure out why they were broken on a new teammate's Mac.

Tried installing from a stable release but got the following error:

```
$ brew install https://raw.githubusercontent.com/apiaryio/drafter/v2.1.2/tools/homebrew/drafter.rb
######################################################################## 100.0%
Error: drafter is a head-only formula
Install with `brew install --HEAD drafter`
```

I agree with [these folks](https://github.com/Homebrew/homebrew-head-only#why-is-head-only-bad) on the matter—as long as this package is head-only, I can't get consistent results out of any scripts I write that use drafter.

**Comment by kylef** [comment]
I was working on making this no longer head-only. The pull request at https://github.com/apiaryio/drafter/pull/187 is required for this.
