### ISSUE TITLE
Drafter binary links to `pthread` but never uses it

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#218]
I'm not sure where `-lpthread` is coming from, I didn't find any mention of `pthread` in the whole repository. Does anyone have any idea?

```shell
$ ldd src/drafter-v2.1.2/bin/drafter 
	linux-vdso.so.1 (0x00007fffbfd5a000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7b4aa50000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7b4a83a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7b4a61d000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f7b4a279000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f7b49f7b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7b4add2000)
```

Found by archlinux's namcap (to verify package):

```shell
$ namcap drafter-2.1.2-1-x86_64.pkg.tar.xz 
drafter W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/bin/drafter')
```

**Comment by w-vi** [comment]
@kylef It comes from this file https://github.com/apiaryio/snowcrash/blob/master/common.gypi#L100

**Comment by klokane** [comment]
I don't know it come from snowcrash. Probably some historical reason. Just speculation: required by node.js? Maybe @zdne can remember?

**Comment by zdne** [comment]
No idea :/

**Comment by w-vi** [comment]
So it looks like nobody remebers the reason, let's remove it then.
