### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by w-vi** [apiaryio/drafter#261]
Current master that is 46f2dbac4dc38bbc20f429f9de8cd53364d7e65f has memory leaks, see https://gist.github.com/w-vi/3046fbe681d921a752b3 for details. Some are in tests which is not a big issue though.

**Comment by w-vi** [comment]
Updated memcheck log can be found at https://circle-artifacts.com/gh/apiaryio/drafter/792/artifacts/0/home/ubuntu/drafter/memcheck.log

**Comment by pksunkara** [comment]
This is fixed in master
