### ISSUE TITLE
Generate an older version of ast that has resourceGroups

### ISSUE THREAD

**Issue by ashee** [apiaryio/drafter#281]
I have used drafter with -t ast. The output needs to be fed to another tool that expects resourceGroups. Is it possible to generate an older version of the ast?

**Comment by kylef** [comment]
Hi @ashee, this isn't possible. The only way you can get older versions of the AST is if you use an older version of Snowcrash / Drafter that exports these AST versions.

Curious, which version are you looking to generate? [resourceGroups](https://github.com/apiaryio/api-blueprint-ast#blueprint-object) is in the latest version of the AST (4.0).

I want to point out that the AST is actually deprecated and you should consider moving to [Refract API Elements](http://api-elements.readthedocs.org/en/latest/) in the future.

**Comment by pksunkara** [comment]
I am closing this for now. Please reopen if needed. Thanks.
