### ISSUE TITLE
Fixed type can't be optional?

### ISSUE THREAD

**Issue by joelanders** [apiaryio/drafter#311]
```
# Data Structures
# App

- id (required)
- dependencies (array[number], fixed, optional)
```
gives me
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "dependencies": {
      "type": "array",
      "items": [
        {
          "type": "number"
        }
      ]
    }
  },
  "required": [
    "id",
    "dependencies"
  ]
}
```
I'm using `fixed` per your suggestion here: https://github.com/apiaryio/drafter/issues/310

I'm trying to make an optional array of numbers.

Thanks again!

**Comment by pksunkara** [comment]
I think you can try something like this:

```apis
- dependencies (array, optional)
    - (number, fixed)
```

**Comment by joelanders** [comment]
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "dependencies": {
      "type": "array"
    }
  },
  "required": [
    "id"
  ]
}
```
It loses the
```
    "dependencies": {
      "type": "array",
      "items": [
        {
          "type": "number"
        }
      ]
    }
```
part that I need :(

**Comment by kylef** [comment]
That's right, fixed keyword means that the instances of this type structure has values that are fixed. Therefore having both `fixed` and `optional` together doesn't make sense. You're saying that the array MUST have fixed numbers. If they are fixed, they cannot be optional.

I think what you are looking to is something else, which is not fixed and covered by https://github.com/apiaryio/mson/issues/66.
