### ISSUE TITLE
Non valid behavior for attribute `- key: value (object)`

### ISSUE THREAD

**Issue by klokane** [apiaryio/drafter#318]
For following blueprint
```
# GET /
- Response 200 (application/json)
    - Attribute (A)

# Data Structures

## A
- myObject: abc (object)
```

I will receive message
```
warning: (1)  unable to render JSON/JSONSchema. Invalid member type of object in MSON definition :11:32
```

Expected behavior is report invalid syntax for definition `- myObject: abc (object)`

**Comment by w-vi** [comment]
This I think requires to have semantical check phase in drafter, as this is syntactically correct but because it is an object it doesn't make sense.
