### ISSUE TITLE
Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by abowen** [apiaryio/drafter#320]
I'm on a Windows 10 64 bit machine, running Node v4.4.3

After loading up over a dozen Markdown files, I get the following error

    "Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.") at Error
    at jsStackTrace (C:\dev\tpa\tpa\ing-pages\node_modules\drakov\node_modules\drafter.js\emcc\drafter.nomem.js:1:20966

Any easy fix is for me to go in into the node_node_modules\drafter.js\emcc\drafter.nomem.js, by replacing 16777216 (16MB) with 536870912 (512MB).

This issue is also reported here, which is the tool I'm using
https://github.com/Aconex/drakov/issues/126

And I've seen similar behavior in other tools of changing the makefile
https://github.com/kripken/sql.js/issues/113

Is this a suitable solution or are there better alternatives?

**Comment by pksunkara** [comment]
I think we can increase the memory. @w-vi What do you think?

**Comment by w-vi** [comment]
We can set `ALLOW_MEMORY_GROWTH=1` so that this won't be happening.

**Comment by w-vi** [comment]
This has been fixed in https://github.com/apiaryio/drafter.js/pull/42 and is waiting for release, so I keep this open until the release.

**Comment by ilkerguller** [comment]
I got the same update. It works after @abowen fix

**Comment by w-vi** [comment]
@ilkerguller It depends on your needs but having the fixed amount of memory means that it is allocated no matter what. The fix on drafter.js is more flexible, it allows the memory top grow if needed but starts with the 16MB which for most of the API Blueprints is enough. I'm considering increasing the base size of the memory so it fits even more cases as the memory allocation takes time.

**Comment by w-vi** [comment]
dratfer.js has been released.
