### ISSUE TITLE
"Missing title" warning doesn't appear in situations where title is clearly missing

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#321]
There's missing [title warning](https://github.com/apiaryio/snowcrash/blob/b381e30d20615accfcb19a0ec574b9c785bdebd7/src/BlueprintParser.h#L296). It becomes an error if user turns it on via options, so the same problem probably applies to the error as well, but I tested the behavior with warning only.

The problem is that the warning won't get triggered in some situations when it clearly should get triggered. See examples below.

This will trigger the warning:

```apib
So Long, and Thanks for All the Fish!
```

...but this won’t:

```apib
FORMAT: 1A
```

...nor this one:

```apib
## Example [/]
```

...nor this one:

```apib
FORMAT: 1A
## Example [/]
```

When I parse the blueprints, I get Refract where the title is represented by empty string, which, in my opinion, should be considered as missing title:

```
"element": "category",
      "meta": {
        "classes": [
          "api"
        ],
        "title": ""
      },
```

The problem isn't a serious bug obviously, but IMHO it radically lowers usefulness of the warning. The warning appears just for blueprint which actually isn't blueprint at all, so now it rather indicates invalid input than missing title.

**Comment by kylef** [comment]
I think this is intentional. If the `require API name` flag wasn't set. The warning only appears if you have a description without an API name.

Since the API description should sit under an API heading. If a user doesn't provide a description then the API name warning wouldn't appear as it's only shown when there is a description and no name.

**Comment by pksunkara** [comment]
@kylef is correct. I just remembered this.

**Comment by honzajavorek** [comment]
Ah, so it's not "warning about missing title". It's "warning if you provide top-level description of the API, but without heading". Do I understand it correctly?

**Comment by pksunkara** [comment]
Yes.

**Comment by honzajavorek** [comment]
Okay, thanks!
