### ISSUE TITLE
Multiple responses with same content

### ISSUE THREAD

**Issue by w-vi** [apiaryio/drafter#337]
Following APIB is not producing a warning that the response `401`  is already defined

```
# A [/a]

## X [GET]

+ Response 401 (application/json)

            {
                code" : ”Eo2”,
            }


+ Response 401 (application/json)

            {
                code" : ”Eo2”,
            }
```

**Comment by pksunkara** [comment]
I think non-200 responses are allowed many times. Not sure though. This simply can be a bug.

**Comment by kylef** [comment]
We don't even warn for multiple 200 responses with the same content type too.

```apib
# Resource [/]
## Foo [GET]

+ Response 200 (plain/text)

        Hello World

+ Response 200 (plain/text)

        Hello World

+ Response 204
+ Response 204
```

```
$ drafter test.apib -l

OKAY.

$ drafter --version
v2.3.1
```

**Comment by pksunkara** [comment]
Ah, I forgot about the content-types. Yes, it is a bug. We should warn if status codes and content types are the same.

**Comment by w-vi** [comment]
Funnily enough if you put `+ Body` there it starts to complain :)

**Comment by kylef** [comment]
Should we issue a warning here? I might legitimately want to have examples showing how different requests might result in the same response.

For example:

```apib
# Login [POST /login]

+ Attributes
    + username: kyle
    + password: passie

+ Request (application/json)
    + Attributes
    
+ Response 200 (application/json)
    + Attributes
        + token: 123abc
        
+ Request Incorrect Password (application/json)
    + Attributes
    + Body

            { "username": "kyle", "password": "incorrect" }
    
+ Response 401 (application/json)

        { "error": "Username or Password is incorrect" }
        
+ Request Unknown Username (application/json)
    + Attributes
    + Body

            { "username": "root", "password": "passie" }
    
+ Response 401 (application/json)

        { "error": "Username or Password is incorrect" }
```

**Comment by pksunkara** [comment]
I agree with kyle

**Comment by w-vi** [comment]
Yes, that was the initial idea, we should give warning ... also we should have some way how to suppress warning of some type so the output is not cluttered if it is a legitimate use but produces warning. But that's different story.

**Comment by kylef** [comment]
We've decided that this doesn't have much impact and it is purely effecting the aesthetics of the API Blueprint source file. The redundancy in duplicate response doesn't affect the semantic meaning of the blueprint.
