### ISSUE TITLE
Remove "echo" in install script

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/drafter#339]
When installing `drafter.js`, [this line](https://github.com/apiaryio/drafter/blob/master/package.json#L7) appears but basically nothing really is happening.

Would it be possible to remove i?

**Comment by w-vi** [comment]
Big things a gwaan see https://github.com/apiaryio/drafter.js/pull/41 . We are separating it and going to cleanup and polish the drafter.js experience.

**Comment by kylef** [comment]
This has been fixed in https://github.com/apiaryio/drafter.js/pull/41
