### ISSUE TITLE
Error in compiling on Win8 LNK1104 cannot open file kernel32.lib

### ISSUE THREAD

**Issue by mjza** [apiaryio/drafter#34]
Dear all,

I want to use drafter on win 8 but it has lots of problem when I want to compile it on windows.

1- First of all with VS Express you don't have Command line compiler. Then I needed to install the full version. See the error below:

    C:\Users\xxx\Documents\GitHub\drafter>vcbuild.bat
    creating config.gypi
    creating config.mk
    creating makefiles
    Warning: Missing input files:
    ./build\ext\snowcrash\..\..\..\ext\snowcrash\src\Version.h
    All OK.
    Project files generated.
    ERROR: Cannot determine the location of the VS Common Tools folder.
    Build skipped. To build, this file needs to run from VS cmd prompt.

After that I installed the Visual studio full version. And when I wanted to compile it by running vcbuild.bat in the step "8>InitializeBuildStatus: ClCompile" I got the following error:

    ---------------------------
    cl.exe - Systemfehler
    ---------------------------
    Das Programm kann nicht gestartet werden, da mspdb110.dll auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben. 
    ---------------------------
    

It is in German but means can not find mspdb110.dll file. I found the file in the following location and add it to the system path to solve this problem:

    C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE

But at the moment there are 2 new problem that I couldn't solve them by adding anymore address to the path:

The first problem:

     10>c:\users\xxxi\documents\github\drafter\test\vendor\catch\include
    \internal\catch_console_colour_impl.hpp(29): fatal error C1083: 
    Cannot open include file: 'windows.h': No such file or directory (..\test\test-main.cc)
    [C:\Users\xxx\Documents\GitHub\drafter\build\test-libdrafter.vcxproj]

And the second one:

     9>LINK : fatal error LNK1104: cannot open file 'kernel32.lib'         
    [C:\Users\xxx\Documents\GitHub\drafter\build\drafter.vcxproj]

Please help me. I also asked this question with some pictures here:

    http://stackoverflow.com/questions/29878710/how-to-install-apiaryio-drafter-on-windows-8

But no any useful answer come up!

Thanks in advance.

**Comment by XVincentX** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE``

I am afraid this is not the directory you should add to your path.
Try to have a look at `$(USERPROFILE)\appdata\local\microsoft\msbuild\v4.0`and read the .users.props file

**Comment by kylef** [comment]
@mjza Did you manage to figure anything out regarding this issue?

**Comment by mjza** [comment]
I gave it up. I decided to not deal with it anymore, because I couldn't install it successfully.

**Comment by w-vi** [comment]
We have changed the windows build using latest VS so I thinks this does not apply anymore, will close this one and feel free to reopen if you encounter this issue
