### ISSUE TITLE
Potential memory leak when `getSchema()` is not called within JSON Schema visitor

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#352]
This was flagged by the Clang static analyser.

<img width="876" alt="screen shot 2016-06-28 at 14 29 30" src="https://cloud.githubusercontent.com/assets/44164/16417843/61a7d5bc-3d3f-11e6-834b-f9a6e8e39f67.png">

**Comment by tjanc** [comment]
- fixed in PR #552, PR #577, both already merged to master
