### ISSUE TITLE
Adding drafter as a dependency for a node application

### ISSUE THREAD

**Issue by jbrauchler** [apiaryio/drafter#359]
Is there a way that I can add drafter as a dependency, in my package.json file using the drafter-Head download from homebrew?

**Comment by w-vi** [comment]
For this we have either pure javascript package (drafter.js)[https://github.com/apiaryio/drafter.js] or a native binding (protagonist)[https://github.com/apiaryio/protagonist]. They are following drafter releases.

**Comment by jbrauchler** [comment]
Hmm okay thank you.
