### ISSUE TITLE
Inheritance and Member type precedence not working

### ISSUE THREAD

**Issue by jmatsushita** [apiaryio/drafter#366]
I've seen a number of inheritance fixing pull requests and issues, but I'm not sure if I understand whether the MSON spec is supposed to be implemented in that regard.

In particular the [member type precedence](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#54-member-type-precedence) doesn't seem to work for me with `protagonist@1.4.1` which if I understand correctly includes `drafter@3.0.0`.

Using the same example as in the spec (augmented with some descriptions):
```
# MyType

- person (Person)
    - `last_name` (optional) - Last name

# Person (object, fixed)
- `first_name` - First name
- `last_name` - override me
- address (object) - Address

```

Piped through `refract.py` gives:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "person": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "description": "First name"
        },
        "last_name": {
          "type": "string",
          "description": "override me"
        },
        "address": {
          "type": "object",
          "properties": {},
          "additionalProperties": false,
          "description": "Address"
        }
      },
      "required": [
        "first_name",
        "last_name",
        "address"
      ],
      "additionalProperties": false
    }
  }
}
```

According to the doc, `last_name` shouldn't be required no? In addition shouldn't the description of `last_name` be `"Last name"`?

**Comment by jmatsushita** [comment]
Hi @pksunkara, is that a bug or did I miss something?

**Comment by pksunkara** [comment]
@jmatsushita Thanks for the report. This is definitely a bug.

**Comment by jmatsushita** [comment]
Hi @pksunkara, have you been able to reproduce and maybe look into this?

**Comment by kylef** [comment]
@jmatsushita Yes, we've confirmed this bug. It's on our agenda to fix and it's one of the next up bugs which we will hopefully tackle in the next two weeks.

When we're expanding and rendering the JSON Schema for an MSON property in Drafter, we're not taking into account some of the overridden attributes (description, type, etc) which we will need to fix. Thanks for reporting.
