### ISSUE TITLE
Variable Property Name doesn't seem to be correctly implemented

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#367]
If I try to parse

```apib
FORMAT: 1A

# Beehive API

## Honey [/honey]

### Retrieve [GET]

+ Response 200 (application/json)

    + Attributes

        + todosById
            + *8*
                + text: Prepare Dinner (string, required)
```

with `drafter@3.0.0`, I get

#### JSON

```json
{
  "todosById": {
    "8": {
      "text": "Prepare Dinner"
    }
  }
}
```

#### JSON Schema

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "todosById": {
      "$ref": "#/definitions/8"
    }
  },
  "definitions": {
    "8": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        }
      },
      "required": [
        "text"
      ]
    }
  }
}
```

I think the schema is incorrect, because the property has [Variable Property Name](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#322-variable-property-name), but the schema looks like it forces you to have a property called `8` exactly. In my opinion this is a bug.

--------------------

This issue was filed as an outcome of investigation of https://github.com/apiaryio/dredd/issues/534

**Comment by w-vi** [comment]
The schema is not enforcing name property name to `8`, the definition has some name in this case it is called `8` but could be anything, but it is still incorrect because the JSON and JSON Schmea do not match. The JSOn Schema expects 

```json
{
  "todosById": {
      "text": "Prepare Dinner"
   }
}
```
and the generated JSON has actually one more level of nesting.

**Comment by pksunkara** [comment]
The JSON rendering is correct as it is. `text` should be nested under `8`.

**Comment by w-vi** [comment]
the `text` should be nested under something not necessarily `8`, to be precise.

**Comment by pksunkara** [comment]
True, but since we are not faking data, in this example, it will be nested under `8`.

**Comment by honzajavorek** [comment]
I agree with Pavan. The MSON says it can be any property name and Schema
should reflect that (doable by all-catching regexp pattern property in JSON
Schema, I remember implementing it in boutique.js).

JSON correctly provides a sample property 8 as specified in MSON in place
of "anything".
