### ISSUE TITLE
Should required array generates items section of json schema?

### ISSUE THREAD

**Issue by goganchic** [apiaryio/drafter#371]
If I marked array as required, should its items be in result json schema?
https://github.com/apiaryio/drafter/blame/master/src/refract/JSONSchemaVisitor.cc#L320 this code says that it should, but according to rfc - it should not.

**Comment by pksunkara** [comment]
@kylef Can you give your input here?

**Comment by pksunkara** [comment]
No, if you marked array as `required`, it's items shouldn't be in JSON Schema. You can remove this part of code completely, https://github.com/apiaryio/drafter/blob/master/src/refract/JSONSchemaVisitor.cc#L469-L480
