### ISSUE TITLE
Tests on Windows is crashing.

### ISSUE THREAD

**Issue by Karciukass** [apiaryio/drafter#377]
![image](https://cloud.githubusercontent.com/assets/19343765/17805139/a86cbab8-6606-11e6-95e3-698d018430a3.png)
And here is test output.txt file
[output.txt](https://github.com/apiaryio/drafter/files/426679/output.txt)

**Comment by kylef** [comment]
@Karciukass We are running continuous integration on Windows (https://ci.appveyor.com/project/Apiary/drafter/branch/master) and it's currently passing for master. 

```
Time Elapsed 00:00:01.31
Running tests...
===============================================================================
All tests passed (132 assertions in 257 test cases)
```

Could you please provide a bit more information on your environment such as the exact platform and which compiler you are using.

**Comment by pksunkara** [comment]
@Karciukass Any update on this?
