### ISSUE TITLE
Error: JSON schema validates value as String if no type is given

### ISSUE THREAD

**Issue by netmilk** [apiaryio/drafter#38]
When you provide following MSON which is [interpreted in MSON documentation](https://github.com/apiaryio/mson/blob/46081361555a77f2085b89d53b1418a982c10122/README.md#objects--arrays) as a key with `null` value.

```
### Some object definition
- someKeyWithNoAdditionalSpec
```

it results into this JSON schema wth a `string` type:

```json
{  
   "type":"object",
   "properties":{  
      "someKeyWithNoAdditionalSpec":{  
         "type":"string"
      }
   },
   "$schema":"http://json-schema.org/draft-04/schema#"
}
```

It should only validate presence of the key until [support of `null` primitive type in MSON](https://github.com/apiaryio/mson/issues/26) imho.

**Comment by pksunkara** [comment]
@netmilk The default type is `string`. So, the schema is indeed correct in this case.

**Comment by pksunkara** [comment]
```apib
### Some object definition
- someKeyWithNoAdditionalSpec
```

is equivalent to

```apib
### Some object definition
- someKeyWithNoAdditionalSpec (string)
```

**Comment by pksunkara** [comment]
I am closing this since we have already replied and @netmilk didn't post any objections.

**Comment by w-vi** [comment]
@pksunkara why it has been reopened?

**Comment by pksunkara** [comment]
I don't remember why. Maybe I was waiting for `nullable` support? Closing this now.
