### ISSUE TITLE
Invalid JSON schema for fixed-type arrays 

### ISSUE THREAD

**Issue by paumoreno** [apiaryio/drafter#389]
The following input:

```
## Test [/Test]

+ Attributes (object)
    
    + id: 12 (number) - List identifier
    + name: Films you must watch (string, required) - List description
    + medias (array[string], fixed-type) - References to the medias in the list

# GET /
+ Response 200 (application/json)
    + Attributes (Test)
```

Generates this JSON schema:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "number",
      "description": "List identifier"
    },
    "name": {
      "type": "string",
      "description": "List description"
    },
    "medias": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ],
      "description": "References to the medias in the list"
    }
  },
  "required": [
    "name"
  ]
}
```

Note that there is a [tuple validation](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation) for the `medias` array.

In this snippet:

```
      "items": [
        {
          "type": "string"
        }
      ],
```

The validator is saying "the first item of the array should be a string".

Instead, as I understand from the MSON spec, `array[string], fixed-type` means that all items of the array should be a string.

The expected output, thus, should be a [List Validation](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#list-validation) schema:

```
      "items": {
        "type": "string"
      },
```

**Comment by pksunkara** [comment]
@goganchic Would you look at this once? Thanks.

**Comment by goganchic** [comment]
ok, I'll take a look at this bug
