### ISSUE TITLE
Escaping parameter names and values fails

### ISSUE THREAD

**Issue by w-vi** [apiaryio/drafter#391]
Following  APIB produces warning on the first parameter
`warning: (3)  unable to parse additional parameter traits, expected '([required | optional], [<type> | enum[<type>])', e.g. '(optional, string)'; line 8, column 7 - line 8, column 38`

If the escaping takes place on the parameter name as well as example value it fails. 

```apib
# A

## A [/a{?u_u,u}]

### Get A [GET]

+ Parameters 
    + `u_u` (required, string, `a_a`)
    + u (required, string, `a_a`)

+ Response 200

```

**CURRENT WORKAROUND**
Use different syntax for the example:

```apib
    + `u_u`: `a_a` (required, string)
```

**Comment by pksunkara** [comment]
Old parameter format doesn't support escaping for the parameter name. This is intentional.

**Comment by w-vi** [comment]
Huh, what? Why? Is it documented somewhere? I haven't found it.

**Comment by pksunkara** [comment]
Old parameter format is not an MSON format. Escaping as a concept only exists in MSON. Old parameter format is deprecated currently.

**Comment by w-vi** [comment]
I see, so we should issue deprecation warning I suppose as this is confusing.

**Comment by pksunkara** [comment]
We currently support both formats albeit one of them without being the spec. MSON parameters and headers RFC should take care of this later.

I am closing this for now.

**Comment by w-vi** [comment]
This is not solved really, as it is nowhere to be seen that I am using deprecated feature.

**Comment by pksunkara** [comment]
It is not deprecated yet. But there is no mention of the old format anywhere in the spec.

**Comment by w-vi** [comment]
So lets clarify it somehow (spec, docs, warning) and then we can close it.
