### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by danorr** [apiaryio/drafter#403]
I've tried following the instructions for building on Windows. Installed VS Studio Express 2015 for windows 10, cloned the repo and get the following error when trying to build:

`drafter>vcbuild.bat
creating config.gypi
creating config.mk
creating makefiles
C:\Python27\python.exe: can't open file 'ext/snowcrash/tools/gyp/gyp_main.py': [Errno 2] No such file or directory
All OK.
Failed to create vc project files.`

The repo is on a network document share which I haven't managed to navigate to through the cmd prompt. 

Any help much appreciated. Let me know if you need any more information.

Cheers,
Dan

**Comment by w-vi** [comment]
Did you do recursive clone as it seems that the `snowcrash` dependency is missing. Can you verify that the file `ext/snowcrash/tools/gyp/gyp_main.py` exists?

**Comment by danorr** [comment]
Yes, that's exactly it. Have rerun the git clone command but again have failures to clone certain submodules, which I suspect will have to do with the corporate firewall. Which means it won't run until those files are there. Thanks for the prompt response.

**Comment by w-vi** [comment]
Would a source tarball solve it for you? https://github.com/apiaryio/drafter/releases/download/v3.1.1/drafter-v3.1.1.tar.gz

**Comment by danorr** [comment]
It may well do. Thanks so much for the follow up! I will give it a try with fresh eyes. 


Dan Orr 






On Mon, Oct 3, 2016 at 9:23 PM +1300, "Vilibald" <notifications@github.com> wrote:












Would a source tarball solve it for you? https://github.com/apiaryio/drafter/releases/download/v3.1.1/drafter-v3.1.1.tar.gz

**Comment by w-vi** [comment]
Closing as it seems to be solved, if not please feel free to reopen.
