### ISSUE TITLE
Can not build on Windows

### ISSUE THREAD

**Issue by Karciukass** [apiaryio/drafter#410]
Hi, I've tried following the instructions for building on Windows, but still get this error: 
C:\git\drafter>vcbuild.bat
creating config.gypi
creating config.mk
creating makefiles
All OK.
Project files generated.
Build skipped. To build, this file needs to run from VS cmd prompt.
 I use VS 2015

**Comment by kylef** [comment]
@Karciukass I don't see any error there. What problem are you are hitting?

**Comment by Karciukass** [comment]
Hello, so why I get this:
[image: Įterptasis vaizdas 1]

I have same problem on two computers.
but i made everything like in tutorial.

2016-10-13 0:25 GMT+03:00 Kyle Fuller <notifications@github.com>:

**Comment by w-vi** [comment]
Maybe we are missing something in the instructions because this line looks suspicious.

> Build skipped. To build, this file needs to run from VS cmd prompt.

**Comment by Karciukass** [comment]
maybe you can check, because I really need this in this week, please help..

2016-10-13 9:44 GMT+03:00 Vilibald <notifications@github.com>:

**Comment by Voyowsky** [comment]
Runnin from VS 2015/2015 developers cmd and Windows cmd
> C:\drafter-repo\drafter>vcbuild.bat
creating config.gypi
creating config.mk
creating makefiles
All OK.
Project files generated.
Building Snow Crash...
Build started 3/29/2017 6:39:39 PM.
     1>Project "C:\drafter-repo\drafter\build\drafter.sln" on node 1 (default t
       argets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Win32".
     1>Project "C:\drafter-repo\drafter\build\drafter.sln" (1) is building "C:\
       drafter-repo\drafter\build\drafter.vcxproj.metaproj" (2) on node 1 (defa
       ult targets).
     2>Project "C:\drafter-repo\drafter\build\drafter.vcxproj.metaproj" (2) is
       building "C:\drafter-repo\drafter\build\libsos.vcxproj" (6) on node 4 (d
       efault targets).
     6>InitializeBuildStatus:
         Creating "Release\obj\libsos\libsos.unsuccessfulbuild" because "Always
         Create" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsos.vcxproj -> C:\drafter-repo\drafter\build\Release\lib\libsos.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsos\libsos.unsuccessfulbuild".
         Touching "Release\obj\libsos\libsos.lastbuildstate".
     6>Done Building Project "C:\drafter-repo\drafter\build\libsos.vcxproj" (de
       fault targets).
     2>Project "C:\drafter-repo\drafter\build\drafter.vcxproj.metaproj" (2) is
       building "C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxpr
       oj" (5) on node 2 (default targets).
     5>InitializeBuildStatus:
         Touching "Release\obj\libsnowcrash\libsnowcrash.unsuccessfulbuild".
     2>Project "C:\drafter-repo\drafter\build\drafter.vcxproj.metaproj" (2) is
       building "C:\drafter-repo\drafter\build\libdrafter.vcxproj" (7) on node
       3 (default targets).
     7>InitializeBuildStatus:
         Creating "Release\obj\libdrafter\libdrafter.unsuccessfulbuild" because
          "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libdrafter.vcxproj -> C:\drafter-repo\drafter\build\Release\lib\libdra
         fter.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libdrafter\libdrafter.unsuccessfulbuild".
         Touching "Release\obj\libdrafter\libdrafter.lastbuildstate".
     7>Done Building Project "C:\drafter-repo\drafter\build\libdrafter.vcxproj"
        (default targets).
     1>Project "C:\drafter-repo\drafter\build\drafter.sln" (1) is building "C:\
       drafter-repo\drafter\build\test-libdrafter.vcxproj.metaproj" (4) on node
        1 (default targets).
     4>Project "C:\drafter-repo\drafter\build\test-libdrafter.vcxproj.metaproj"
        (4) is building "C:\drafter-repo\drafter\build\ext\snowcrash\libsundown
       .vcxproj" (8) on node 4 (default targets).
     8>InitializeBuildStatus:
         Creating "Release\obj\libsundown\libsundown.unsuccessfulbuild" because
          "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
       Lib:
         All outputs are up-to-date.
         libsundown.vcxproj -> C:\drafter-repo\drafter\build\Release\lib\libsun
         down.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libsundown\libsundown.unsuccessfulbuild".
         Touching "Release\obj\libsundown\libsundown.lastbuildstate".
     8>Done Building Project "C:\drafter-repo\drafter\build\ext\snowcrash\libsu
       ndown.vcxproj" (default targets).
     4>Project "C:\drafter-repo\drafter\build\test-libdrafter.vcxproj.metaproj"
        (4) is building "C:\drafter-repo\drafter\build\ext\snowcrash\libmarkdow
       nparser.vcxproj" (9) on node 1 (default targets).
     9>InitializeBuildStatus:
         Creating "Release\obj\libmarkdownparser\libmarkdownparser.unsuccessful
         build" because "AlwaysCreate" was specified.
       ClCompile:
         All outputs are up-to-date.
     5>ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /
         I"..\..\..\ext\snowcrash\ext\markdown-parser\src" /I"..\..\..\ext\snow
         crash\ext\markdown-parser\ext\sundown\src" /Zi /nologo /W1 /WX- /Od /O
         b2 /Oi /Ot /Oy /GL /D BUILDING_SNOWCRASH=1 /D WIN32 /D _CRT_SECURE_NO_
         DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /Gm- /EHsc /MD /GS /Gy /fp:prec
         ise /Zc:wchar_t /Zc:forScope /GR /Fo"Release\obj\libsnowcrash\\" /Fd"R
         elease\obj\libsnowcrash\vc110.pdb" /Gd /TP /analyze- /errorReport:queu
         e /MP ..\..\..\ext\snowcrash\src\Signature.cc ..\..\..\ext\snowcrash\s
         rc\snowcrash.cc
     9>Lib:
         All outputs are up-to-date.
         libmarkdownparser.vcxproj -> C:\drafter-repo\drafter\build\Release\lib
         \libmarkdownparser.lib
       FinalizeBuildStatus:
         Deleting file "Release\obj\libmarkdownparser\libmarkdownparser.unsucce
         ssfulbuild".
         Touching "Release\obj\libmarkdownparser\libmarkdownparser.lastbuildsta
         te".
     9>Done Building Project "C:\drafter-repo\drafter\build\ext\snowcrash\libma
       rkdownparser.vcxproj" (default targets).
     5>ClCompile:
         Signature.cc
         snowcrash.cc
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C20
       59: syntax error : '{' (..\..\..\ext\snowcrash\src\snowcrash.cc) [C:\dra
       fter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C21
       43: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash\src\sn
       owcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vc
       xproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C21
       43: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash\src\sn
       owcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vc
       xproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\MSONNamedTypeParser.h(19): war
       ning C4129: '(' : unrecognized character escape sequence (..\..\..\ext\s
       nowcrash\src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\
       libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\MSONNamedTypeParser.h(19): war
       ning C4129: '{' : unrecognized character escape sequence (..\..\..\ext\s
       nowcrash\src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\
       libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C20
       59: syntax error : '{' (..\..\..\ext\snowcrash\src\Signature.cc) [C:\dra
       fter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C21
       43: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash\src\Si
       gnature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vc
       xproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ActionParser.h(317): error C21
       43: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash\src\Si
       gnature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vc
       xproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2059: syntax error : '{' (..\..\..\ext\snowcrash\src\snowcrash
       .cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2143: syntax error : missing ';' before '{' (..\..\..\ext\snow
       crash\src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\lib
       snowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2143: syntax error : missing ';' before '}' (..\..\..\ext\snow
       crash\src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\lib
       snowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\MSONNamedTypeParser.h(19): war
       ning C4129: '(' : unrecognized character escape sequence (..\..\..\ext\s
       nowcrash\src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\
       libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\MSONNamedTypeParser.h(19): war
       ning C4129: '{' : unrecognized character escape sequence (..\..\..\ext\s
       nowcrash\src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\
       libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2059: syntax error : '{' (..\..\..\ext\snowcrash\src\snowcrash.cc) [C:\d
       rafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2143: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash\src\
       snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.
       vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2143: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash\src\
       snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.
       vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2059: syntax error : '{' (..\..\..\ext\snowcrash\src\Signature
       .cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2143: syntax error : missing ';' before '{' (..\..\..\ext\snow
       crash\src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\lib
       snowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\DataStructureGroupParser.h(112
       ): error C2143: syntax error : missing ';' before '}' (..\..\..\ext\snow
       crash\src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\lib
       snowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2059: syntax error : '{' (..\..\..\ext\snowcrash\src\Signature.cc) [C:\d
       rafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2143: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash\src\
       Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.
       vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceParser.h(267): error C
       2143: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash\src\
       Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.
       vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2059: syntax error : '{' (..\..\..\ext\snowcrash\src\snowcrash.cc)
       [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2143: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash
       \src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowc
       rash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2143: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash
       \src\snowcrash.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowc
       rash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2059: syntax error : '{' (..\..\..\ext\snowcrash\src\Signature.cc)
       [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowcrash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2143: syntax error : missing ';' before '{' (..\..\..\ext\snowcrash
       \src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowc
       rash.vcxproj]
     5>c:\drafter-repo\drafter\ext\snowcrash\src\ResourceGroupParser.h(208): er
       ror C2143: syntax error : missing ';' before '}' (..\..\..\ext\snowcrash
       \src\Signature.cc) [C:\drafter-repo\drafter\build\ext\snowcrash\libsnowc
       rash.vcxproj]
     5>Done Building Project "C:\drafter-repo\drafter\build\ext\snowcrash\libsn
       owcrash.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\drafter-repo\drafter\build\drafter.vcxproj.met
       aproj" (default targets) -- FAILED.
     4>Done Building Project "C:\drafter-repo\drafter\build\test-libdrafter.vcx
       proj.metaproj" (default targets) -- FAILED.
     1>Done Building Project "C:\drafter-repo\drafter\build\drafter.sln" (defau
       lt targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:02.11

**Comment by FernandoWahl** [comment]
Hello, this problem is still happening to me. Any news?

**Comment by sheryltech** [comment]
I'm stuck at Step 6. Run vcbuild.bat. How can I proceed? 

> C:\Users\sheryl\drafter>vcbuild.bat
> creating config.gypi
> creating config.mk
> creating makefiles
> All OK.
> Project files generated.
> Build skipped. To build, this file needs to run from VS cmd prompt.

**Comment by panigrc** [comment]
I have the same problem.

> Build skipped. To build, this file needs to run from VS cmd prompt.

**Comment by kylef** [comment]
We've switched to a different build system which should hopefully bring a more consistent experiance to all our supported platforms.

The installation instructions in the README have been updated for Windows (see https://github.com/apiaryio/drafter#installation). Please give this a try and create a new issue if you're having any problems with the CMake instructions for Windows.
