### ISSUE TITLE
Warn if a fixed-type array contains more than one item

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/drafter#415]
Because it goes against the intention of `fixed-type`

**Comment by w-vi** [comment]
How do I express n-tuple of certain types then?

**Comment by pksunkara** [comment]
Enum in array.

**Comment by pksunkara** [comment]
Can you give me an example?

**Comment by kylef** [comment]
What about:

```apib
+ Attributes
    + sourceMap (array, fixed-type)
        + (int) - start range
        + (int) - length

**Comment by pksunkara** [comment]
I think a better example would be something like the following: (start, length, filename)

```
"sourceMap": ["28", "10", "main.apib"]
```

In this case, we can write something like this:

```
+ sourceMap (array, fixed-type)
    + (enum)
        + (int) - Start range
        + (int) - Length
        + (string) - File name
```

**Comment by w-vi** [comment]
Canonical example
```
    + Attributes
        + address (array, fixed-type)
            + (string) - street
            + (number) - number
            + (string) - city
     
```

**Comment by pksunkara** [comment]
I want to clarify something. `      "items": [` fixes the type of the items inside?

**Comment by w-vi** [comment]
`items` means a tuple validation, see https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation

**Comment by pksunkara** [comment]
Well then, we don't need to warn. We can support JSON Schema for this. I thought we couldn't do this with JSON Schema.

**Comment by w-vi** [comment]
I think current behaviour is correct and expected.

**Comment by pksunkara** [comment]
Okay. Closing this issue.
