### ISSUE TITLE
Sample value not allowed to be null

### ISSUE THREAD

**Issue by jyggen** [apiaryio/drafter#420]
(not sure if this belongs here or in [Snow Crash](https://github.com/apiaryio/snowcrash))

Recently I've started to receive a warning in my API blueprints whenever I use `null` as the sample value for a MSON property, as seen with the property `parent` in the example below.

```apib
FORMAT: 1A

# Group Messages

## Messages [/messages]

### List [GET]
List all messages.

+ Response 200 (application/json)
    + Attributes (Message)

# Data Structures

## Message

+ message: Foo Bar Baz Qux (string, required)
+ parent: null (number, required, nullable)
```

```shell
$ drafter -l example.apib

OK.
warning: (4)  invalid value format for 'number' type. please check mson specification for valid format :231:42
```

Is this intended or am I simply doing something wrong? Thanks! :)

**Comment by w-vi** [comment]
We have tighten up the type checks a bit and `null` is not a valid number format so that's why you are getting the warning but on the other hand because it is `nullable` you can skip the sample value and the JSON example will actually show `null` as the example value.

**Comment by jyggen** [comment]
So it does, and here I thought I had already tried that. Thanks a bunch!
