### ISSUE TITLE
Output "default" MSON as "default" JSON Schema 

### ISSUE THREAD

**Issue by jmatsushita** [apiaryio/drafter#424]
Hi there,

Currently MSON defaults are only emitted as `application/json` content and not as `application/schema+json` which reminds me of #392.

Related to our use apiaryio/mson#70 use case I would like to be able to export MSON Defaults as described [here](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#45-default), for example:

```
 - deleted: false (boolean, required, default)
```

as JSON Schema defaults that are part of the [JSON Schema Validation spec](http://json-schema.org/latest/json-schema-validation.html#anchor101) in this way:

```
    "deleted": {
      "type": "boolean",
      "default": false
    }
```

Which will enable us to deal with the [*Boolean Gotcha* for the form generator](https://github.com/mozilla-services/react-jsonschema-form/issues/48#issuecomment-199671252) we use and avoid empty required boolean checkboxes to be seen as `undefined` and be seen as `false` instead.

![image](https://cloud.githubusercontent.com/assets/356097/19926173/6c651b00-a0f3-11e6-8356-12ee8772e9bc.png)

**Comment by kylef** [comment]
Looking at the MSON Spec, it actually says:

> Indicates Values for Member Types as a nested Markdown list with (multi-line) text are defaults.
> ...
> A default Type Attribute MUST NOT be used in the Type Definition of a Property Member Declaration.

Which from what I understand, means that `default` can only be used with member types such as `enum`, and `array`. It does seem that default is supported in JSON Schemas for [array](https://github.com/apiaryio/drafter/blob/master/src/refract/JSONSchemaVisitor.cc#L504) and [enum](https://github.com/apiaryio/drafter/blob/master/src/refract/JSONSchemaVisitor.cc#L543) member types.

However, I do not see any reason why we should limit `default` to just these types, it may also make sense to support `default` in an objects property as you've shown in your message.

@zdne I would love to hear your feedback here, perhaps you might have a reason `default` was designed to only be for member types only that I'm not aware of.

**Comment by pksunkara** [comment]
```
+ a: pavan
    + Default: pksunkara
```

That is valid as far as I know.

**Comment by miduddin** [comment]
Sorry for commenting on an old issue. Apparently the issue still exist on latest drafter version (v4.0.0), although i've tried v3.2.0 and it seems to work just fine there.
