### ISSUE TITLE
Include libdrafter installation into Makefile

### ISSUE THREAD

**Issue by menecio** [apiaryio/drafter#426]
Hi,

I've tried to install libdrafter on my Ubuntu machine, although I was able to install drafter binary and pass all tests without issues, I see there is no declaration on Makefile to install libdrafter, like it's defined when installing using Homebrew on macos.

If not, at least could you add some instructions on README.md to successfully install libdrafter on Linux-based machines?

**Comment by klokane** [comment]
Hi, we are sorry about it. In current version is `libdrafter` little bit cosmetic then usable library.
We are working on define strict API, then we will update drafter build to build `libdrafter` in corect way

**Comment by kylef** [comment]
There is also a small API for validating and parsing blueprints (drafter.h header contains all the documentation for interface: https://github.com/apiaryio/drafter/blob/master/src/drafter.h).

Its is possible to install drafter as a library but we found it difficult automatic into the Makefile in a cross platform way. We would certainly love to make `make install` install both the library, header and command line tool consistently on each platform in the future.

You could follow the following steps to install the library on linux:

```shell
$ make drafter
```

Then copy over the necessary files into your platform, for example:

- `build/out/Release/libdrafter.so` > `/usr/lib/libdrafter.so`
- `bin/drafter` -> `/usr/bin/drafter`
- `src/drafter.h` `/usr/include/drafter/drafter.h`

You can swap `/usr` to a destination of your choice providing you configure your compilers header and library search paths to point to the destination.

**Comment by kylef** [comment]
This has been addressed, we've switched to CMake build system and it is configured to install the library too. Please give it a go, (the README has been updated with new installation instructions).
