### ISSUE TITLE
Expand json schema for arrays of member types

### ISSUE THREAD

**Issue by hendrikmaus** [apiaryio/drafter#441]
Summary: have drafter expand json schema for nested member types

Example API Blueprint:

- there is one model, `Message`
- first resource returns a collection of `Message`
- second resource returns a single `Message`

```apib
# GET /messages
+ Response (application/json)
    + Attributes (array[Message])

# GET /messages/{id}
+ Parameters
    + id: 42 (number, required)
    
+ Response (application/json)
    + Attributes (Message)

# Data Structures
## Message (object)
+ id: 42 (number, required)
+ body: `Hello World` (string, required)
```

The schema for `# GET /messages` returned by drafter defines the type as `array` rather than expanding the `Message` member type.

**Current result:**
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array"
}
```

**Expected result:**
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "body": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "body"
    ]
  }
}
```

As we explicitly tell drafter that the response is an array of `Message`, it should be able to build the respective schema.

**Comment by kylef** [comment]
Hi @hendrikmaus,

I don't think I understand what your feature request is, could you please clarify?

**Comment by hendrikmaus** [comment]
@kylef my bad, I refactored my proposal.

**Comment by pksunkara** [comment]
@hendrikmaus You need to use `fixed-type` to say that the array is strictly conforming.

```
+ Attributes (array[Message], fixed-type)
```

**Comment by hendrikmaus** [comment]
@pksunkara brilliant! thanks for the quick reply.

One note for the team: I used atom as a playground and re-installed the latest version of https://atom.io/packages/linter-api-blueprint (v0.4.0) which seems to compile an older drafter version as it warns me about that very attribute:

```json
{
      "element": "annotation",
      "meta": {
        "classes": [
          "warning"
        ]
      },
      "attributes": {
        "code": 5,
        "sourceMap": [
          {
            "element": "sourceMap",
            "content": [
              [
                68,
                40
              ]
            ]
          }
        ]
      },
      "content": "ignoring unrecognized type attribute"
    }
```

**Comment by pksunkara** [comment]
https://github.com/zdne/linter-api-blueprint/blob/master/package.json#L24 needs to be updated to new version.
