### ISSUE TITLE
set flag required by default for json-schema

### ISSUE THREAD

**Issue by batizhevsky** [apiaryio/drafter#451]
Hi
I think there is little misbehavior  between drafter and apib specification
In [documentation](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#description-13) said that `required` is default flag for parameter

but in the builtin schema this parameter set only if it set explicitly  in apib 
example:

```
# GET /sample
+ Response 200 (application/json)
    + Attributes (Message)

# Data Structures

# Message
+ text1 (string)
+ text2 (string, required)
+ text3 (string, optional)
````

result (only output schema for short):
```
{
   "[GET]/sample" : [
      {
         "schema" : {
            "required" : [
               "text2"
            ],
            "$schema" : "http://json-schema.org/draft-04/schema#",
            "properties" : {
               "text3" : {
                  "type" : "string"
               },
               "text1" : {
                  "type" : "string"
               },
               "text2" : {
                  "type" : "string"
               }
            },
            "type" : "object"
         },
         "meta" : {
            "type" : "response",
            "title" : null
         }
      }
   ]
}
```

drafter -v
v3.2.2

installed from brew (os x)

**Comment by w-vi** [comment]
The default `required` applies to URI Parameters like `/user/{id}/create`. `+ Attributes (Message)` is not parameter in this sense here. It is a response.

**Comment by kylef** [comment]
Yes, MSON `attributes` are optional by default (https://apiblueprint.org/documentation/mson/specification.html#353-type-attribute).
