### ISSUE TITLE
JSON schema generated for nullable enums is incorrect

### ISSUE THREAD

**Issue by JeppeKnockaert** [apiaryio/drafter#455]
An issue was posted over at https://github.com/apiaryio/dredd/issues/507. I believe the root cause is that the JSON schema generated for nullable enums is incorrect.

# Used blueprint

```
# Test route [GET /test]

+ Response 200 (application/json)
    + Attributes (Item)

# Data Structures

## Item (object)

- type (Type, nullable)

## Type (enum)

- type1
- type2
```

# Resulting JSON schema

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "type1",
        "type2"
      ]
    }
  }
}
```

# JSON expected to be valid

```
{
  "type": null
}
```

# Conclusion

The JSON expected to be valid is invalid if verified against the genereated schema, as you can see here: https://jsonschemalint.com/#/version/draft-04/markup/json?gist=22cb20d97158bce3b1a632ef165b6db6

Options I'm seeing right now:
- Allow to specify null as an enum value (now it is automatically converted to a string)
- If nullable is specified on an enum, automatically add null as a possible enum value

**Comment by w-vi** [comment]
@JeppeKnockaert  Thanks a lot for inspecting. Way forward is to make it `null` part of the enum possible values as that is what makes logical sense.
