### ISSUE TITLE
Reserved URI parameter "not found"

### ISSUE THREAD

**Issue by jackbentley** [apiaryio/drafter#456]
This warning appears when using a parameter with `+` at the beginning (the *reserved value operator*). It shouldn't because [it's valid according to the spec](https://apiblueprint.org/documentation/specification.html#variable-with-reserved-characters-values)?

```
warning: (8)  parameter 'file' is not found within the URI template '/blah/{prefix}/files/{+file}'
```

**Comment by pksunkara** [comment]
Yes, it's valid according to the spec. Unfortunately, our URI template implementation has a few bugs.

**Comment by kylef** [comment]
As of [Drafter 5.0.0-rc.1](https://github.com/apiaryio/drafter/releases/tag/v5.0.0-rc.1), full support for URI Template has been added, including level 3/4.

URI Templates such as `/blah/{prefix}/files/{+file}` are now supported.
