### ISSUE TITLE
Cannot install from Homebrew on OSX

### ISSUE THREAD

**Issue by victorbello** [apiaryio/drafter#457]
Getting this error when executing the command provided.

`> brew install --HEAD \`
`  https://raw.github.com/apiaryio/drafter/master/tools/homebrew/drafter.rb`
`######################################################################## 100.0%`
`==> Cloning https://github.com/apiaryio/drafter.git`
`Updating /Users/victorbello/Library/Caches/Homebrew/drafter--git`
`==> Checking out tag v3.2.3`
`Synchronizing submodule url for 'ext/markdown-parser'`
`Synchronizing submodule url for 'test/vendor/Catch'`
`Synchronizing submodule url for 'ext/sundown'`
`Synchronizing submodule url for 'test/ext/Catch'`
`Synchronizing submodule url for 'test/ext/Catch'`
`fatal: unable to connect to github.com:`
`github.com[0: 192.30.253.113]: errno=Connection refused`
`github.com[1: 192.30.253.112]: errno=Connection refused`

`fatal: clone of 'git://github.com/philsquared/Catch.git' into submodule path` `'/Users/victorbello/Library/Caches/Homebrew/drafter--git/ext/sos/test/ext/Catch' failed`
`Failed to clone 'test/ext/Catch'. Retry scheduled`
`fatal: unable to connect to github.com:`
`github.com[0: 192.30.253.113]: errno=Connection refused`
`github.com[1: 192.30.253.112]: errno=Connection refused`

`fatal: clone of 'git://github.com/philsquared/Catch.git' into submodule path` `'/Users/victorbello/Library/Caches/Homebrew/drafter--git/ext/sos/test/ext/Catch' failed`
`Failed to clone 'test/ext/Catch' a second time, aborting`
`Failed to recurse into submodule path 'ext/sos'`
`Error: Failed to download resource "drafter"`
`Failure while executing: git submodule -q update --init --recursive`

**Comment by pksunkara** [comment]
@victorbello Looks like you were having network issues when installing. Please try again after ensuring your internet connection is stable.
