### ISSUE TITLE
Homebrew installs v3.2.3

### ISSUE THREAD

**Issue by SMillerDev** [apiaryio/drafter#464]
It seems to check out the master branch, which is 3 versions behind on the formula.

Maybe #215 could fix this?

**Comment by kylef** [comment]
#215 would certainly fix this.

For now you can install the stable branch via:

```shell
$ brew install --HEAD \
  https://raw.github.com/apiaryio/drafter/stable/3.x/tools/homebrew/drafter.rb
```

**Comment by SMillerDev** [comment]
I'd also love to maintain a package in homebrew for this if you think it's beneficial. I'm keeping track of new versions for my linux PC anyways.

**Comment by pksunkara** [comment]
@SMillerDev How are you keeping track of linux PC versions?

**Comment by SMillerDev** [comment]
@pksunkara manually editing the PKGBUILD file for Arch whenever I see a new release in my RSS feed.
