### ISSUE TITLE
Improper serialization of dataStructures

### ISSUE THREAD

**Issue by sjuxax** [apiaryio/drafter#466]
Uploaded some samples of bad conversion output from drafter 3.2.6 at https://github.com/sjuxax/drafter-bug-demo.

See https://github.com/refractproject/minim-api-description/issues/25 and https://github.com/refractproject/minim-api-description/issues/18 for further discussion.

```
$ drafter --version
v3.2.6
```

**Comment by sjuxax** [comment]
Any news on this?

**Comment by kylef** [comment]
This has been fixed in master via https://github.com/apiaryio/drafter/pull/478 and will be released soon as Drafter 4.

**Comment by pksunkara** [comment]
Closing this as there is a pre-relase out.
