### ISSUE TITLE
HOST parsing is inconsistent for Blueprint / Swagger

### ISSUE THREAD

**Issue by michalholasek** [apiaryio/drafter#481]
There is an inconsistency how drafter parses declared HOST in Blueprint and Swagger.

Given I use `My Invalid URL` as an URL, I get no errors at all for Blueprint:

<img width="1278" alt="screen shot 2017-06-28 at 16 13 39" src="https://user-images.githubusercontent.com/2771467/27641784-30d335fa-5c1d-11e7-8c9f-1eee933da926.png">

...but I get parsing error for Swagger:

<img width="1280" alt="screen shot 2017-06-28 at 16 12 41" src="https://user-images.githubusercontent.com/2771467/27641833-4ee8825c-5c1d-11e7-869b-a31fa4a2ff3c.png">

I think it would be a good idea to have it consistent (at least to some degree) for both formats.

**Comment by kylef** [comment]
@michalholasek As far as the parser and API Blueprint language are concerned, the key value pairs at the top of [API Blueprint are purely metadata](https://apiblueprint.org/documentation/specification.html#def-metadata-section). The language itself doesn't defined `HOST`, that is purely an extension that Apiary is using.

**Comment by michalholasek** [comment]
@kylef I am aware of this, I filed this issue after a conversation with @pksunkara to start a discussion about this topic.

**Comment by pksunkara** [comment]
Basically, the question here is, are we satisfied with it being inconsistent?

**Comment by w-vi** [comment]
What has drafter to do with this? Tools using HOST should take care of it.
