### ISSUE TITLE
An explode ("*") modifier isn't recognized in the URI Template

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#500]
Drafter now seems to support arrays in URI parameters, but it fails to recognize the explode ("*") modifier and returns a warning. Example API Blueprint:

```apib
FORMAT: 1A

# Beehive API

## Honey [/honey{?beekeeper,flavour*}]

+ Parameters
    + beekeeper: Honza (enum[string], optional)

        Description...

        + Members
            + Adam
            + Honza
            + Dredd
        + Default: Dredd

    + flavour: sweet (array[string])
        + Members
            + sweet
            + spicy

### Remove [DELETE]

+ Request (application/json)

+ Response 200

```

The warning:

```
parameter 'flavour' is not found within the URI template '/honey{?beekeeper,flavour*}' for 'Honey'
```

**Comment by honzajavorek** [comment]
First, I learned API Blueprint / Drafter doesn't support arrays as URI Parameters, so this issue should be formulated as a feature request, not as a bug report. Second, there are some problems with semantics of the URI Template, see https://github.com/apiaryio/dredd/issues/791. I'm closing this.

**Comment by kylef** [comment]
Linking in https://github.com/apiaryio/snowcrash/issues/357 regarding `*` operator. Regarding array support, I think that would be tracked via full MSON support in Parameters (https://github.com/apiaryio/api-blueprint-rfcs/pull/3).
