### ISSUE TITLE
Compatibility with different platforms and frameworks

### ISSUE THREAD

**Issue by chilio** [apiaryio/drafter#522]
This package seems a nice way to go and I find it a really interesting piece of code.
Many packages already depend on it already.
But unfortunately digging it deeper, it is failing to properly install under other platforms then **OSX**.
Hey @apiaryio any plans on making it more cross platform? 
If you would like to address these issues, please consider **laravel** and **homestead** for example.
Deployment is another issue, but I'm sure that everyone, would be more than happy, to have documentation, on how to install it, on different systems.

**Comment by w-vi** [comment]
It works well under any Linux too. What would you like to see as supported platfom?

**Comment by chilio** [comment]
My problem was, installing it, with composer hmaus/drafter-installer, under Windows 10 development machine, with laravel homestead on virtualbox. I was receiving error (even when installing manually), while creating symbolic link inside this homestead box. 
Running it with admin rights solved my problem.
But on the other hand, it would be nice, if I could install this from package for windows also, instead of building it.
