### ISSUE TITLE
Unnamed datastructure shouldn't be possible

### ISSUE THREAD

**Issue by char0n** [apiaryio/drafter#523]
When creating a ADD like this one, parser will parse it fine, but it will create un-referenced data-structure (no meta/no id) in refract tree. Can the parser ignore structures like these and give us warning/error when it intercepts something like that ?

```apib
FORMAT: 1A
HOST: http://localhost:8085

# Hello API

## /api/v2/transaction
Initialize a new transaction
+ Attributes
    + clientReference (string, optional)
```

**Comment by pksunkara** [comment]
The fix should be that we give a warning about needing the resource name and then ignore the attributes section.

**Comment by char0n** [comment]
Getting back to this. Apiary has already compensated for this issue on it's documentation as seen here: https://pdaapi1.docs.apiary.io/.

Rethinking it again, maybe we should allow users to do things like these. Documentation can already render, parser can parse, let's keep the behavior as it is. Or do you see any other reason why this should be considered as warning or error ?

**Comment by kylef** [comment]
I agree, le't s close this.
