### ISSUE TITLE
Drafter will not successfully build with macOS Command Line Tools

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#540]
#### Expected Behaviour

I am able to build drafter with the command line tools on macOS which contain the compiler and build dependencies.

#### Actual Behaviour

Seems the build process is hitting xcodebuild which results in the following error as xcodebuild requires Xcode:

```
$ ./configure
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/'
```

It shouldn't be necessary to use xcodebuild, this could perhaps be a limitation of gyp.

#### Steps to Reproduce

1) Ensure CommandLineTools are installed.
1) Ensure that `xcode-select -p` returns `/Library/Developer/CommandLineTools`.
    - `sudo xcode-select -s /Library/Developer/CommandLineTools` can be used to select CL Tool if Xcode is instead selected.
1) Clone repository for Drafter and run `./configure`.

**Comment by pksunkara** [comment]
This is fixed with testing using xcode9 on circleci

**Comment by kylef** [comment]
@pksunkara This issue is about using CLI Tools and not Xcode so I don't see how Xcode 9 on CircleCI is relevant here?

**Comment by pksunkara** [comment]
Travis has `os: mac` option

**Comment by kylef** [comment]
@pksunkara Travis also has Xcode pre-installed. None of our CI environments test without Xcode installed. The steps to reproduce this issue in my description do work.

**Comment by kylef** [comment]
With the introduction of CMake installation, this problem is no longer applicable.
