### ISSUE TITLE
Clone repository stuck on Catch submodule

### ISSUE THREAD

**Issue by nfgallimore** [apiaryio/drafter#544]
When trying to clone the repository recursively it gets caught on this submodule and then errors out and says it schedules the task for later.

![image](https://user-images.githubusercontent.com/4875906/40250765-59cdc132-5aa5-11e8-9e32-45754601ed23.png)

**Comment by nfgallimore** [comment]
It appears that they released Catch 2 and the repository for philsquared is non existent.

**Comment by kylef** [comment]
When repositories are moved on GitHub, GitHub provide a redirect so the existing URLs should still work as seen by:

```shell
$ curl -I https://github.com/philsquared/Catch
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Date: Fri, 18 May 2018 20:43:37 GMT
...
Location: https://github.com/catchorg/Catch2
```

I've confirmed this behaviour is working on CI by re-building (https://circleci.com/gh/apiaryio/drafter/1767):

<img width="1002" alt="screen shot 2018-05-18 at 14 42 34" src="https://user-images.githubusercontent.com/44164/40257003-bbe9f71a-5aa9-11e8-8f09-8eb87f4ed930.png">

It's odd this isn't working for you though, we should update the submodule path.

**Comment by kylef** [comment]
Catch provides a single header file in Catch2 for including. Perhaps it makes sense to start vendoring the single header (+ LICENSE) as needed.

https://github.com/catchorg/Catch2/releases/download/v2.2.2/catch.hpp

**Comment by nfgallimore** [comment]
Where should I put the header file? Also maybe it's because I am on Windows. Can we confirm it works on Windows? 

![image](https://user-images.githubusercontent.com/4875906/40547935-428c0c48-6001-11e8-9983-a6e320593eeb.png)

**Comment by kylef** [comment]
@nfgallimore We've updated the repo URL in the project now. If you pull the changes and update the submodules it should all work.

**Comment by nfgallimore** [comment]
Git clone recursive is still failing even with the new update to the submodule url.

The .gitmodules file has no reference to the philsquared url yet it is still going to it for some reason.

![image](https://user-images.githubusercontent.com/4875906/40658964-dae02148-631a-11e8-9184-c7ef8a4c3a84.png)

**Comment by pksunkara** [comment]
Oh, the philsquared Catch is being used in other submodules too.

**Comment by pksunkara** [comment]
https://github.com/apiaryio/sos/blob/master/.gitmodules
