### ISSUE TITLE
Bad Error Message

### ISSUE THREAD

**Issue by goganchic** [apiaryio/drafter#547]
I've opened MSON specification and found such example https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#232-value-member-types so I've created such piece of code:

```
# Tesla

## Users [POST /users]

+ Response 200 (application/json)
    + Attributes
        + (array)
            + foo
            + bar
```

I use drafter from master and it reports me such an error:

> drafter: ../src/refract/Element.h:76: const DataType& refract::Element< <template-parameter-1-1> >::get() const [with DataType = refract::dsd::String]: Assertion `hasValue_' failed.

Is it bug or I've done something wrong?

P.s. such example works fine:

```
# Tesla

## Users [POST /users]

+ Response 200 (application/json)
    + Attributes (array)
        + foo
        + bar
```

**Comment by pksunkara** [comment]
You have done something wrong. `Attributes` is an object, but you gave it a value member with `(array)`. The error should have a better message though.

**Comment by goganchic** [comment]
ok, thanks!

**Comment by pksunkara** [comment]
No, we need to keep this open to have a better error message.

**Comment by goganchic** [comment]
ok

**Comment by kylef** [comment]
The following patch will restore Drafter 3.2.7 behaviour. Although I do not think this is correct and we should likely catch the problem earlier. I think `GetKeyAsString()` should require an actual key to be there as it does in master. @tjanc what do you think? 

```diff
diff --git a/src/refract/VisitorUtils.cc b/src/refract/VisitorUtils.cc
index 8192a8c9..6a1d2b08 100644
--- a/src/refract/VisitorUtils.cc
+++ b/src/refract/VisitorUtils.cc
@@ -27,7 +27,9 @@ std::string refract::GetKeyAsString(const MemberElement& e)
     auto element = e.get().key();

     if (auto str = TypeQueryVisitor::as<const StringElement>(element)) {
-        return str->get();
+        if (!str->empty()) {
+            return str->get();
+        }
     }

     if (auto ext = TypeQueryVisitor::as<const ExtendElement>(element)) {
```
