### ISSUE TITLE
Win10 build error

### ISSUE THREAD

**Issue by Ge11ert** [apiaryio/drafter#550]
OS: Windows 10 x64 (version 10.0.16299 build 16299) (HP notebook if it does matter)

I had cloned latest version of Drafter from master. Then executed `vcbuild.bat` and got this build log:

```
creating config.gypi
creating config.mk
creating makefiles
Warning: Missing input files:
./build\..\src\ElementInfoUtils.hsrc\ElementComparator.hsrc\utils\Variant.h
All OK.
Project files generated.
Building Snow Crash...
Build started 06.06.2018 12:50:22.
     1>Project C:\Users\gellert\....\drafter\build\drafter.sln" on node 1 (Build target(s)).
     1>C:\Users\gellert\...\drafter\build\drafter.sln.metaproj : error MSB4126: 
The specified solution configuration "Release|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties 
(e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.
     1>Done Building Project "C:\Users\gellert\...\drafter\build\drafter.sln" (Build target(s)) -- FAILED.
```

After searching some hints and possible fix variants, I came to this:

If I edit `vcbuild.bat` on line 122 as shown further, it works:
```
msbuild build/drafter.sln /m /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /property:Configuration=%config%;Platform=Win32
```

I tried to `SET Platform=` at the top of the script, to specify `Platform=x64`, but only `Platform=Win32` works. 

Just information for you and maybe for someone who could encounter this problem in the future.

**Comment by chilio** [comment]
I believe it is too long path on windows (although I have long paths enabled)....
I cannot even copy this project dir to another place.... :(

**Comment by kylef** [comment]
Thanks for reporting @Ge11ert, it's a little tricky for us to keep on top of Windows support, it has been very problematic for some users to install and none of the active maintainers run that platform. Although we do stride to support Windows and use CI to test on Windows.

If there is anyone from the community willing to help out with Windows testing and support we'd greatly appreciate it (and any pull requests).

**Comment by kylef** [comment]
We've switched to a different build system which should hopefully bring a more consistent experiance to all our supported platforms.

The installation instructions in the README have been updated for Windows (see https://github.com/apiaryio/drafter#installation). Please give this a try and create a new issue if you're having any problems with the CMake instructions for Windows.
