### ISSUE TITLE
Explode modifier not supported?

### ISSUE THREAD

**Issue by SMillerDev** [apiaryio/drafter#553]
I'm trying to use the explode modifier with drafter: https://tools.ietf.org/html/rfc6570#section-2.4.2
but I can't get it to work. The API Blueprint spec mentions that RFC6570 is supported though.

*Error message:*
> warning: (8)  parameter 'filter' is not found within the URI template '/flights{?filter*}' for 'Flight list'

*Code:*
```apib
### Flight list [GET /flights{?filter*}]

Get a filtered list of flights

+ Parameters
    + filter (required) - Provide one of these values as a parameter to filter
        + arrival : `false` (optional) - Whether the flight is an arrival or departure
        + terminal : `A` (optional) - The terminal for the flight
        + gate : `5` (optional) - Gate information
```

**Comment by kylef** [comment]
The URI Template support is a bit lacking at the moment. I'd like to schedule looking into URI Template support near-term. There are various related problems, linking in #500, #456, https://github.com/apiaryio/api-blueprint/issues/252 and https://github.com/apiaryio/snowcrash/issues/357.

Right now we're focussed on getting Drafter 4 changes finished and rolled out across Apiary and I think this can be fixed shortly afterwards once we got 4.0 out.

**Comment by SMillerDev** [comment]
I know it's open source and whatnot but I'm gonna try asking for a schedule either way 😉 .
What timeline should I think of for 4.0? Weeks? Months? Before 2030?

**Comment by kylef** [comment]
Weeks I hope, #552 should be on of the last PRs (pending any problems we discover during testing). Once that's ready and merged we can being rolling out which will be a delicate and slow process as there are some significant changes to the parse result and we need to be careful rolling out to Apiary and be sure we are not introducing regressions or performance problems.

**Comment by kylef** [comment]
As of [Drafter 5.0.0-rc.1](https://github.com/apiaryio/drafter/releases/tag/v5.0.0-rc.1), full support for URI Template has been added, including level 3/4 and the explode modifier.

The included document will now parse without warnings, and show something along the lines of the following in [ApiaryUI](https://blog.apiary.io/ApiaryUI):

![Screenshot 2020-03-23 at 09 35 02](https://user-images.githubusercontent.com/44164/77302749-b9e20a80-6ce9-11ea-8fc5-b58d0515fe76.png)
