### ISSUE TITLE
Strange error for incorrect document

### ISSUE THREAD

**Issue by goganchic** [apiaryio/drafter#556]
I'm looking throw function [parseTypeSpecification](https://github.com/apiaryio/snowcrash/blob/master/src/MSONUtility.h#L187) and try to find out how Drafter process such invalid document:

```
# My API

# Data Structures

# Foo[Hello]

+ a
+ b

# GET /foo

+ Response 200 (application/json)
    + Attributes (array[Foo[Hello]], fixed-type)
```

When I start Drafter I get such error:

```
./bin/drafter test.apib
Assertion failed: (hasValue_), function get, file ../src/refract/Element.h, line 70.
[1]    55413 abort      ./bin/drafter test.apib
```

So I have several questions:

* Is it ok to use brackets in `Named Type` name?
* Is it a valid error for such document?
* What is formal definition of such error? (e.g. I should not use brackets in type definition or something like this)

Used Drafter version: master branch, commit 2318c78d

**Comment by kylef** [comment]
Just to note, Drafter 3.2.7 (stable) parses this document without producing any warnings or errors.

One problem in the document is that you have not placed `Foo[Hello]` in a `Data Structures` section so subsequently it is treated as the description of the `My API`. If the definition was moved to a  Data Structures section then you'd see a warning to escape the name as it contains reserved characters of `[` and `]`.

Didn't look into it much further but does look like a regression in master that we should address. Not sure if the behaviour in 3.2.7 is correct either though.

**Comment by goganchic** [comment]
@kylef sorry, I've forgot to insert `Data Structures` section when copy/paste code into ticket. I've fixed ticket description. Error is the same.

**Comment by pksunkara** [comment]
Definitely a regression.

**Comment by kylef** [comment]
Yes, I've created internal issue in JIRA to tracks this. The problem is with referencing unknown types in `array[]`. The minimal document is the following:

```apib
FORMAT: 1A

# GET /

+ Response 200 (application/json)
    + Attributes (array[Unknown])
```

We'll schedule into upcoming engineering sprint and get this fixed.
