### ISSUE TITLE
JSON Schema generation can contain redundant anyOf entries for fixed-type arrays

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#566]
The following API Blueprint produces a redundant JSON Schema that contains anyOf containing the same entires multiple times. In this trivial case, could they be de-duplicated in the JSON Schema providing an array of `fixed-type`?

```apib
# GET /

+ Response 200 (application/json)
    + Attributes
        + direction: north, east, south, west (array[string, array], fixed-type)
```

```shell
$ ./bin/drafter test.apib -f json | ./tools/refract-filter.py

OK.
{
  "direction": [
    "north"
  ]
}
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "direction": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "array"
          }
        ]
      }
    }
  }
}
```

**Comment by tjanc** [comment]
This is reasonable and I implemented it at first; specifically, my code did this during transformation to JSON Schema. There it incurred a substantial maintainability trade-offs (i. e. the code became too complicated for me to believe I'd like to see it again). I'm standing behind that decision.

Therefore I suggest applying such an optimization after transformation to JSON Schema; that is, on the simple object representation. Something along the lines:

```
namespace refract {
  namespace schema {
    drafter::utils::so::Object reduceJsonSchema(const drafter::utils::so::Object& schema);
    drafter::utils::so::Object reduceJsonSchema(drafter::utils::so::Object&& schema);
  }
}
```
