### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by vivl4725** [apiaryio/drafter#655]
Please add support to Linux subsystem for windows.

I appreciated your work, but I don’t have time to compile the application under windows.

**Comment by tjanc** [comment]
@vivl4725 Are you able to build drafter via CMake on your platform?
```
git clone --recursive https://github.com/apiaryio/drafter
mkdir drafter/build
cd drafter/build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

**Comment by kylef** [comment]
@vivl4725 did the above suggestion work for you?
