### ISSUE TITLE
explode char ("*") only supported once (AND at the end)

### ISSUE THREAD

**Issue by roomsg** [apiaryio/drafter#666]
when using single, trailing explode char in resource, all goes fine
eg:
## GET /res1/{resId}/res2{?start,end,summary,type*}

when using multiple (or non-trailing) explode char in resource, we get the following error: "_contains invalid characters. Allowed characters for expressions are A-Z a-z 0-9 _ and percent encoded characters_" error
eg

**Comment by kylef** [comment]
As of [Drafter 5.0.0-rc.1](https://github.com/apiaryio/drafter/releases/tag/v5.0.0-rc.1) the explode modifier is now supported:

![2020-09-28-151823_388x424_scrot](https://user-images.githubusercontent.com/44164/94444120-de89d400-019d-11eb-89ee-983ffc1173bf.png)
