### ISSUE TITLE
Form-style query continuation operator does not work

### ISSUE THREAD

**Issue by masterada** [apiaryio/drafter#667]
The example stated for form-style query continuation operator [in the docs](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#uri-template-variable) does not work on apiary.io:

```md
# Test

## Test [GET /path/to/resources/{varone}?path=test{&vartwo,varthree}]

+ Parameters
    + varone: `1`
    + vartwo: `2`
    + varthree: `3`

+ Response 200
```

Changing `{&...}` to `{?...}` works, but results in an invalid url (as expected).

**Comment by kylef** [comment]
Are you still seeing any problems? In terms of Drafter, we've changed the URI Template parser in [Drafter 5.0.0-rc.1](https://github.com/apiaryio/drafter/releases/tag/v5.0.0-rc.1), this this version the above is parsed and exposed as I would expect in Apiary documentation without any warnings:

![2020-09-28-153221_461x345_scrot](https://user-images.githubusercontent.com/44164/94445955-f19da380-019f-11eb-9b57-edf5f916dc09.png)

Rendered:

![2020-09-28-153212_464x386_scrot](https://user-images.githubusercontent.com/44164/94445991-fc583880-019f-11eb-989c-bcd22d609120.png)
