### ISSUE TITLE
Windows version control - messaging

### ISSUE THREAD

**Issue by merglv** [apiaryio/drafter#672]
Hi.
You by awesome if you do some edit in error messages in vcbuild.bat script.

1. Problem
U have installed python2.7 and python3 in my computer. I have higher priority to python3 Path then python2. Your script vcbuild.bat calls only "python" no "python2" command as you write in error message about python2 is not installed in computer. Obiviously some message "U have wrong python version" insted of "u dont have installed python in yout pc" will be great

2. Problem
Please add support for VS 2017 or atleast when u cannot find VS 2008 - 2015 dont tell me "start script from VS command line" when i doing it :)

Thx

**Comment by merglv** [comment]
Also, link for downloading VS in your wiki not working, and you write in requirments u support vs 2018 or higher even its not true ;)

**Comment by kylef** [comment]
Hi, yes you're right about the wiki. Those instructions are not that well maintained, neither is Windows support to be honest.

In Drafter master we've added cmake support, which replaces the need for Python 2.7, which can simplify the setup process. All you'll need is a modern C++ compiler and cmake, the instructions on how to use cmake support can be found at https://github.com/apiaryio/drafter/issues/655#issuecomment-435083999.

**Comment by kylef** [comment]
As an alternative, we also offer a pure JavaScript version of the API Blueprint parser. You will be able to parse API Blueprint's using it via Node JS without having to build the C++ parser https://github.com/apiaryio/api-elements.js/tree/master/packages/fury-cli.

**Comment by kylef** [comment]
@merglv did the suggestion in https://github.com/apiaryio/drafter/issues/655#issuecomment-435083999 work for you?
