### ISSUE TITLE
drafter is not recognized as an internal or external command, an executable program, or a batch file.

### ISSUE THREAD

**Issue by KraJacob** [apiaryio/drafter#677]
Hello everyone, first time to use blueprint for the documentation of my laravel api. I followed the laravel-blueprint doc. I installed drafter first as stated in doc. after following all the steps when i try to access the route / api-documentation i have this error api \ vendor / bin / drafter 'is not recognized as an internal or external command, an executable program or a batch file.

**Comment by kylef** [comment]
Hi @KraJacob, could you give us a bit more information such as your platform and how you tried to install Drafter?

**Comment by KraJacob** [comment]
I am under windows, and it is in project laravel 5.7.
I first installed drafter with the require hmaus/drafter-installer. then 
`"extra": {
      "install-drafter": "Hmaus\\Drafter\\Installer::installDrafter",
      "post-install-cmd": [
        "@install-drafter"
      ],
      "post-update-cmd": [
        "@install-drafter"
      ]
    },`

after i install bleuprint `composer require m165437/laravel-blueprint-docs`
`php artisan vendor:publish --provider="M165437\BlueprintDocs\BlueprintDocsServiceProvider" --tag="example"`
`php artisan vendor:publish --provider="M165437\BlueprintDocs\BlueprintDocsServiceProvider" --tag="public"`

it says in the doc that after that I can access the doc on the root api-documentations, but when try to access i got this error  C:\xampp\htdocs\clicseller-api\vendor/bin/drafter' 
is not recognized as an internal or external command, an executable program or a batch file

**Comment by kylef** [comment]
We maintain support for Drafter on Windows with CMake, some instructions you can use to install can be found at https://github.com/apiaryio/drafter/issues/655#issuecomment-435083999.

As for the hendrikmaus/drafter-installer, that's a third part set of tools, you can try asking in their issue tracker: https://github.com/hendrikmaus/drafter-installer.
