### ISSUE TITLE
Drafter aborts while rendering JSON value for a non-object inside an array of objects

### ISSUE THREAD

**Issue by kylef** [apiaryio/drafter#682]
The included API Blueprint caused the assertion at https://github.com/apiaryio/drafter/blob/bb00117c0f96fecc07a89dfc33ebbdd002164eba/src/refract/JsonValue.cc#L95 to be hit:

```
$ ./bin/drafter <document>
Assertion failed: (false), function renderProperty, file ../src/refract/JsonValue.cc, line 95.
fish: './bin/drafter <document>' terminated by signal SIGABRT (Abort)
```

```apib
## GET /

+ Response 200 (application/json)
    + Attributes (array[object])
        + Thing
```

Drafter 4.0.0-pre.3

**Comment by kylef** [comment]
Drafter 3.2.7 succeeds and returns the following JSON body:

```json
[
  {
    "": "Thing"
  }
]
```

It does not produce any error.

**Comment by kylef** [comment]
Another case, perhaps not same bug but it seems related:

```apib
# GET /

+ Response 200 (application/json)
    + Attributes (Array)
        + (object)

## Data Structures

### Array (array)
```

```
Assertion failed: (hasValue_), function get, file ../src/refract/Element.h, line 75.
fish: './bin/drafter 682-1.apib' terminated by signal SIGABRT (Abort)
```

**Comment by tjanc** [comment]
> Another case, perhaps not same bug but it seems related:
> 
> ```
> # GET /
> 
> + Response 200 (application/json)
>     + Attributes (Array)
>         + (object)
> 
> ## Data Structures
> 
> ### Array (array)
> ```
> 
> ```
> Assertion failed: (hasValue_), function get, file ../src/refract/Element.h, line 75.
> fish: './bin/drafter 682-1.apib' terminated by signal SIGABRT (Abort)
> ```

It's independent. See #683
