### ISSUE TITLE
Duplicit value in enumeration

### ISSUE THREAD

**Issue by sixeyes** [apiaryio/drafter#749]
I've been busy with other projects for the last few months but returned to work on my API docs and discovered I now have 16 semantic errors, even though I've not changed the document. The errors are all:

Duplicit value in enumeration
Line xxxx  API Blueprint

They all refer to enumerations declared in Data Structures section

```apib
# Data Structures
## WaveRecord (object)

+ status: `Processed` (enum, required) - The wave status.
    + Members
        + `Draft` - The wave has been created but not queued.
        + `Processed` - The wave has been processed.
        + `Queued` - The wave has been queued but not processed.
```

The error line xxxx in this example refers to the `+ status:` line. If I remove the `Processed` value I get an error indicating I've not supplied a value.

At the moment it's just a semantic error, but I'd like to know what's changed and what I can do to fix the warnings.

**Comment by kylef** [comment]
Hi @sixeyes, I think this looks like a bug in the parser (Drafter). Thank you for reporting, we'll debug this further and get the the bottom of the problem, for now I think you can ignore these warnings in your document.
