### ISSUE TITLE
Well behaved command line tools return >0 on error.

### ISSUE THREAD

**Issue by beporter** [apiaryio/drafter#80]
Might it be appropriate for drafter to exit with a non-zero status if it encountered any errors or warnings during execution? It makes it difficult to script when it does not conform to [common practices](https://en.wikipedia.org/wiki/Exit_status#Shell_and_scripts).

**Comment by pksunkara** [comment]
Blueprint warnings can't be considered as errors. There is some merit to exit with non-zero status on blueprint errors though.

**Comment by kylef** [comment]
I believe drafter already exists non-0 for drafter errors or blueprint errors.

**Comment by pksunkara** [comment]
Yes, I can confirm that is the current case.
