### ISSUE TITLE
MSON - enum improve parsing

### ISSUE THREAD

**Issue by klokane** [apiaryio/drafter#97]
In current version all "value" specification are joined into content, there based on internal discussion there is proposed behavior as following:
```
# Data Structures       
                          
# Enum behavior           
                        
- size1: L (enum) - content ['L']                                                                  
                          
- size2: S, M, L, XL (enum) - content [ 'S', 'M', 'L', 'XL' ]
                        
- size3: L (enum) - sample [['L']], content [ 'S', 'M', 'L', 'XL' ]
    - S                   
    - M                   
    - L                 
    - XL                
                          
- size4: L (enum) - sample [['L']], content [ 'S', 'M', 'L', 'XL' ]
    - S, M, L, XL       
                      
- size5: *L* (enum) - sample [['L']]                                                                   
                  
- size6: L (enum, sample) - sample [['L']]
```

**Comment by pksunkara** [comment]
I don't think `size4` is valid MSON. And I have some doubts regarding the `size3` when compared to `size1`.

**Comment by klokane** [comment]
@pksunkara please argue! 
Idioms like "have some doubts" are not reason why it is wrong (or correct)!

**Comment by pksunkara** [comment]
Sorry about that. I will do that soon. I am just trying some things out before writing a detailed one.

**Comment by pksunkara** [comment]
`enum` is a special thing. If a value is being used for sample or default for an `enum` type, that value should be under the `content`.

```apib
# Data Structures

## Enum behavior

- size1: L (enum) - sample 'L', content ['L']
- size3: L (enum) - sample 'L', content [ 'S', 'M', 'L', 'XL' ]
    - S
    - M
    - L
    - XL
- size5: *L* (enum) - sample 'L', content ['L']
- size6: L (enum, sample) - sample 'L', content ['L']
```

Yes, there is no difference between `size5` and `size6` incase of `enum`.

```apib
- size2: S, M, L, XL (enum) - content [ 'S', 'M', 'L', 'XL' ]
- size4: L (enum) - sample 'L', content [ 'S', 'M', 'L', 'XL' ]
    - S, M, L, XL
```

`size2` and `size4` are different beasts since `S, M, L, XL` for `enum` value in value definition is quite complex. I need to check a few more things before writing more.

**Comment by pksunkara** [comment]
```apib
# Data Structures
## Enum behavior

- size2: S, M, L, XL (enum) - sample ['S', 'M', 'L', 'XL'], content [['S', 'M', 'L', 'XL']]
- size4: L (enum) - sample 'L', content [['S', 'M', 'L', 'XL']]
    - S, M, L, XL
```

Basically, `S, M, L, XL` on a single line should be treated as an array. It should be treated as an array even if `enum[number]` is the specified type specification because it still allows different types to be inside enum.

**Comment by klokane** [comment]
@pksunkara @zdne 
Hi guys I update (in description) proposed format according to our discussion on yesterday.
Please check and +1 if you agree it is correct, to allow start implementation.

Thanks

**Comment by zdne** [comment]
@klokane 

```
- size4: L (enum) - sample [['L']], content [ 'S', 'M', 'L', 'XL' ]
    - S, M, L, XL       
```

Is **not** correct. 

The line:

```
- S, M, L, XL
```

Should be treated as one value (string by default). So it is "sample 'L', content [ 'S, M, L, XL' ]

**Comment by klokane** [comment]
@z ok.
What about this? https://github.com/apiaryio/drafter/blob/master/test/fixtures/mson/nontyped-array-sample.apib#L8

**Comment by pksunkara** [comment]
@klokane That line is a sample of string. We need to fix the bug in snowcrash which is being tracked at https://github.com/apiaryio/snowcrash/issues/286
